#if CLIENT_DLL || GAME_DLL
using Source;
using Source.Common.Commands;
using Source.Common.GarrysMod.Lua;
using Source.Common.Input;
using Source.Common.ShaderAPI;
using Source.Common.ShaderLib;

using static Source.Common.GarrysMod.Lua.ILuaObject;
using static Source.Common.Mathematics.MathLib;

#if CLIENT_DLL
namespace Game.Client.GarrysMod;
#else
namespace Game.Server.GarrysMod;
#endif

public static class LuaEnumsGlobals
{
	public static readonly LuaEnums LuaEnums = new();
	public static readonly LuaGameEnums LuaGameEnums = new();
}

public class LuaEnums : LuaUser
{
	public LuaEnums() => SetUsingLua(true);

	public override void InitLibraries(ILuaInterface lua) {
		ILuaObject global = lua.Global();
		ILuaObject table;

		const string TYPE = "TYPE";
		const string KEY = "KEY";
		const string MOUSE = "MOUSE";
		const string BUTTON_CODE = "BUTTON_CODE";
		const string JOYSTICK = "JOYSTICK";
		const string KEY_XBUTTON = "KEY_XBUTTON";
		const string KEY_XSTICK1 = "KEY_XSTICK1";
		const string KEY_XSTICK2 = "KEY_XSTICK2";
		const string FCVAR = "FCVAR";
		const string EF = "EF";
		const string BLEND = "BLEND";
		const string BLENDFUNC = "BLENDFUNC";

		// These enums are shared across all states.
		global.SetMemberEnumValuePrefixed("TYPE", "INVALID", LuaType.None);
		global.SetMemberEnumValuesPrefixed<LuaType>("TYPE");

		global.SetMemberEnumValuePrefixed(BUTTON_CODE, "INVALID", ButtonCode.Invalid);
		global.SetMemberEnumValuePrefixed(BUTTON_CODE, "NONE", ButtonCode.None);

		global.SetMemberEnumValuePrefixed(KEY, "FIRST", ButtonCode.KeyFirst);
		global.SetMemberEnumValuePrefixed(KEY, "NONE", ButtonCode.KeyNone);
		global.SetMemberEnumValuePrefixed(KEY, "0", ButtonCode.Key0);
		global.SetMemberEnumValuePrefixed(KEY, "1", ButtonCode.Key1);
		global.SetMemberEnumValuePrefixed(KEY, "2", ButtonCode.Key2);
		global.SetMemberEnumValuePrefixed(KEY, "3", ButtonCode.Key3);
		global.SetMemberEnumValuePrefixed(KEY, "4", ButtonCode.Key4);
		global.SetMemberEnumValuePrefixed(KEY, "5", ButtonCode.Key5);
		global.SetMemberEnumValuePrefixed(KEY, "6", ButtonCode.Key6);
		global.SetMemberEnumValuePrefixed(KEY, "7", ButtonCode.Key7);
		global.SetMemberEnumValuePrefixed(KEY, "8", ButtonCode.Key8);
		global.SetMemberEnumValuePrefixed(KEY, "9", ButtonCode.Key9);
		global.SetMemberEnumValuePrefixed(KEY, "A", ButtonCode.KeyA);
		global.SetMemberEnumValuePrefixed(KEY, "B", ButtonCode.KeyB);
		global.SetMemberEnumValuePrefixed(KEY, "C", ButtonCode.KeyC);
		global.SetMemberEnumValuePrefixed(KEY, "D", ButtonCode.KeyD);
		global.SetMemberEnumValuePrefixed(KEY, "E", ButtonCode.KeyE);
		global.SetMemberEnumValuePrefixed(KEY, "F", ButtonCode.KeyF);
		global.SetMemberEnumValuePrefixed(KEY, "G", ButtonCode.KeyG);
		global.SetMemberEnumValuePrefixed(KEY, "H", ButtonCode.KeyH);
		global.SetMemberEnumValuePrefixed(KEY, "I", ButtonCode.KeyI);
		global.SetMemberEnumValuePrefixed(KEY, "J", ButtonCode.KeyJ);
		global.SetMemberEnumValuePrefixed(KEY, "K", ButtonCode.KeyK);
		global.SetMemberEnumValuePrefixed(KEY, "L", ButtonCode.KeyL);
		global.SetMemberEnumValuePrefixed(KEY, "M", ButtonCode.KeyM);
		global.SetMemberEnumValuePrefixed(KEY, "N", ButtonCode.KeyN);
		global.SetMemberEnumValuePrefixed(KEY, "O", ButtonCode.KeyO);
		global.SetMemberEnumValuePrefixed(KEY, "P", ButtonCode.KeyP);
		global.SetMemberEnumValuePrefixed(KEY, "Q", ButtonCode.KeyQ);
		global.SetMemberEnumValuePrefixed(KEY, "R", ButtonCode.KeyR);
		global.SetMemberEnumValuePrefixed(KEY, "S", ButtonCode.KeyS);
		global.SetMemberEnumValuePrefixed(KEY, "T", ButtonCode.KeyT);
		global.SetMemberEnumValuePrefixed(KEY, "U", ButtonCode.KeyU);
		global.SetMemberEnumValuePrefixed(KEY, "V", ButtonCode.KeyV);
		global.SetMemberEnumValuePrefixed(KEY, "W", ButtonCode.KeyW);
		global.SetMemberEnumValuePrefixed(KEY, "X", ButtonCode.KeyX);
		global.SetMemberEnumValuePrefixed(KEY, "Y", ButtonCode.KeyY);
		global.SetMemberEnumValuePrefixed(KEY, "Z", ButtonCode.KeyZ);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_0", ButtonCode.KeyPad0);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_1", ButtonCode.KeyPad1);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_2", ButtonCode.KeyPad2);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_3", ButtonCode.KeyPad3);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_4", ButtonCode.KeyPad4);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_5", ButtonCode.KeyPad5);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_6", ButtonCode.KeyPad6);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_7", ButtonCode.KeyPad7);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_8", ButtonCode.KeyPad8);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_9", ButtonCode.KeyPad9);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_DIVIDE", ButtonCode.KeyPadDivide);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_MULTIPLY", ButtonCode.KeyPadMultiply);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_MINUS", ButtonCode.KeyPadMinus);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_PLUS", ButtonCode.KeyPadPlus);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_ENTER", ButtonCode.KeyPadEnter);
		global.SetMemberEnumValuePrefixed(KEY, "PAD_DECIMAL", ButtonCode.KeyPadDecimal);
		global.SetMemberEnumValuePrefixed(KEY, "LBRACKET", ButtonCode.KeyLBracket);
		global.SetMemberEnumValuePrefixed(KEY, "RBRACKET", ButtonCode.KeyRBracket);
		global.SetMemberEnumValuePrefixed(KEY, "SEMICOLON", ButtonCode.KeySemicolon);
		global.SetMemberEnumValuePrefixed(KEY, "APOSTROPHE", ButtonCode.KeyApostrophe);
		global.SetMemberEnumValuePrefixed(KEY, "BACKQUOTE", ButtonCode.KeyBackquote);
		global.SetMemberEnumValuePrefixed(KEY, "COMMA", ButtonCode.KeyComma);
		global.SetMemberEnumValuePrefixed(KEY, "PERIOD", ButtonCode.KeyPeriod);
		global.SetMemberEnumValuePrefixed(KEY, "SLASH", ButtonCode.KeySlash);
		global.SetMemberEnumValuePrefixed(KEY, "BACKSLASH", ButtonCode.KeyBackslash);
		global.SetMemberEnumValuePrefixed(KEY, "MINUS", ButtonCode.KeyMinus);
		global.SetMemberEnumValuePrefixed(KEY, "EQUAL", ButtonCode.KeyEqual);
		global.SetMemberEnumValuePrefixed(KEY, "ENTER", ButtonCode.KeyEnter);
		global.SetMemberEnumValuePrefixed(KEY, "SPACE", ButtonCode.KeySpace);
		global.SetMemberEnumValuePrefixed(KEY, "BACKSPACE", ButtonCode.KeyBackspace);
		global.SetMemberEnumValuePrefixed(KEY, "TAB", ButtonCode.KeyTab);
		global.SetMemberEnumValuePrefixed(KEY, "CAPSLOCK", ButtonCode.KeyCapsLock);
		global.SetMemberEnumValuePrefixed(KEY, "NUMLOCK", ButtonCode.KeyNumLock);
		global.SetMemberEnumValuePrefixed(KEY, "ESCAPE", ButtonCode.KeyEscape);
		global.SetMemberEnumValuePrefixed(KEY, "SCROLLLOCK", ButtonCode.KeyScrollLock);
		global.SetMemberEnumValuePrefixed(KEY, "INSERT", ButtonCode.KeyInsert);
		global.SetMemberEnumValuePrefixed(KEY, "DELETE", ButtonCode.KeyDelete);
		global.SetMemberEnumValuePrefixed(KEY, "HOME", ButtonCode.KeyHome);
		global.SetMemberEnumValuePrefixed(KEY, "END", ButtonCode.KeyEnd);
		global.SetMemberEnumValuePrefixed(KEY, "PAGEUP", ButtonCode.KeyPageUp);
		global.SetMemberEnumValuePrefixed(KEY, "PAGEDOWN", ButtonCode.KeyPageDown);
		global.SetMemberEnumValuePrefixed(KEY, "BREAK", ButtonCode.KeyBreak);
		global.SetMemberEnumValuePrefixed(KEY, "LSHIFT", ButtonCode.KeyLShift);
		global.SetMemberEnumValuePrefixed(KEY, "RSHIFT", ButtonCode.KeyRShift);
		global.SetMemberEnumValuePrefixed(KEY, "LALT", ButtonCode.KeyLAlt);
		global.SetMemberEnumValuePrefixed(KEY, "RALT", ButtonCode.KeyRAlt);
		global.SetMemberEnumValuePrefixed(KEY, "LCONTROL", ButtonCode.KeyLControl);
		global.SetMemberEnumValuePrefixed(KEY, "RCONTROL", ButtonCode.KeyRControl);
		global.SetMemberEnumValuePrefixed(KEY, "LWIN", ButtonCode.KeyLWin);
		global.SetMemberEnumValuePrefixed(KEY, "RWIN", ButtonCode.KeyRWin);
		global.SetMemberEnumValuePrefixed(KEY, "APP", ButtonCode.KeyApp);
		global.SetMemberEnumValuePrefixed(KEY, "UP", ButtonCode.KeyUp);
		global.SetMemberEnumValuePrefixed(KEY, "LEFT", ButtonCode.KeyLeft);
		global.SetMemberEnumValuePrefixed(KEY, "DOWN", ButtonCode.KeyDown);
		global.SetMemberEnumValuePrefixed(KEY, "RIGHT", ButtonCode.KeyRight);
		global.SetMemberEnumValuePrefixed(KEY, "F1", ButtonCode.KeyF1);
		global.SetMemberEnumValuePrefixed(KEY, "F2", ButtonCode.KeyF2);
		global.SetMemberEnumValuePrefixed(KEY, "F3", ButtonCode.KeyF3);
		global.SetMemberEnumValuePrefixed(KEY, "F4", ButtonCode.KeyF4);
		global.SetMemberEnumValuePrefixed(KEY, "F5", ButtonCode.KeyF5);
		global.SetMemberEnumValuePrefixed(KEY, "F6", ButtonCode.KeyF6);
		global.SetMemberEnumValuePrefixed(KEY, "F7", ButtonCode.KeyF7);
		global.SetMemberEnumValuePrefixed(KEY, "F8", ButtonCode.KeyF8);
		global.SetMemberEnumValuePrefixed(KEY, "F9", ButtonCode.KeyF9);
		global.SetMemberEnumValuePrefixed(KEY, "F10", ButtonCode.KeyF10);
		global.SetMemberEnumValuePrefixed(KEY, "F11", ButtonCode.KeyF11);
		global.SetMemberEnumValuePrefixed(KEY, "F12", ButtonCode.KeyF12);
		global.SetMemberEnumValuePrefixed(KEY, "CAPSLOCKTOGGLE", ButtonCode.KeyCapsLockToggle);
		global.SetMemberEnumValuePrefixed(KEY, "NUMLOCKTOGGLE", ButtonCode.KeyNumLockToggle);
		global.SetMemberEnumValuePrefixed(KEY, "SCROLLLOCKTOGGLE", ButtonCode.KeyScrollLockToggle);
		global.SetMemberEnumValuePrefixed(KEY, "LAST", ButtonCode.KeyLast);
		global.SetMemberEnumValuePrefixed(KEY, "COUNT", ButtonCode.KeyCount);

		global.SetMemberEnumValuePrefixed(MOUSE, "FIRST", ButtonCode.MouseFirst);
		global.SetMemberEnumValuePrefixed(MOUSE, "LEFT", ButtonCode.MouseLeft);
		global.SetMemberEnumValuePrefixed(MOUSE, "RIGHT", ButtonCode.MouseRight);
		global.SetMemberEnumValuePrefixed(MOUSE, "MIDDLE", ButtonCode.MouseMiddle);
		global.SetMemberEnumValuePrefixed(MOUSE, "4", ButtonCode.Mouse4);
		global.SetMemberEnumValuePrefixed(MOUSE, "5", ButtonCode.Mouse5);
		global.SetMemberEnumValuePrefixed(MOUSE, "WHEEL_UP", ButtonCode.MouseWheelUp);
		global.SetMemberEnumValuePrefixed(MOUSE, "WHEEL_DOWN", ButtonCode.MouseWheelDown);
		global.SetMemberEnumValuePrefixed(MOUSE, "LAST", ButtonCode.MouseLast);
		global.SetMemberEnumValuePrefixed(MOUSE, "COUNT", ButtonCode.MouseCount);

		global.SetMemberEnumValuePrefixed(JOYSTICK, "FIRST", ButtonCode.JoystickFirst);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "FIRST_BUTTON", ButtonCode.JoystickFirstButton);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "LAST_BUTTON", ButtonCode.JoystickLastButton);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "FIRST_POV_BUTTON", ButtonCode.JoystickFirstPovButton);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "LAST_POV_BUTTON", ButtonCode.JoystickLastPovButton);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "FIRST_AXIS_BUTTON", ButtonCode.JoystickFirstAxisButton);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "LAST_AXIS_BUTTON", ButtonCode.JoystickLastAxisButton);
		global.SetMemberEnumValuePrefixed(JOYSTICK, "LAST", ButtonCode.JoystickLast);

		global.SetMemberEnumValuePrefixed(BUTTON_CODE, "LAST", ButtonCode.Last);
		global.SetMemberEnumValuePrefixed(BUTTON_CODE, "COUNT", ButtonCode.Count);

		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "UP", ButtonCode.KeyXButtonUp);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "RIGHT", ButtonCode.KeyXButtonRight);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "DOWN", ButtonCode.KeyXButtonDown);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "LEFT", ButtonCode.KeyXButtonLeft);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "A", ButtonCode.KeyXButtonA);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "B", ButtonCode.KeyXButtonB);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "X", ButtonCode.KeyXButtonX);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "Y", ButtonCode.KeyXButtonY);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "LEFT_SHOULDER", ButtonCode.KeyXButtonLeftShoulder);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "RIGHT_SHOULDER", ButtonCode.KeyXButtonRightShoulder);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "BACK", ButtonCode.KeyXButtonBack);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "START", ButtonCode.KeyXButtonStart);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "STICK1", ButtonCode.KeyXButtonStick1);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "STICK2", ButtonCode.KeyXButtonStick2);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK1, "RIGHT", ButtonCode.KeyXStick1Right);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK1, "LEFT", ButtonCode.KeyXStick1Left);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK1, "DOWN", ButtonCode.KeyXStick1Down);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK1, "UP", ButtonCode.KeyXStick1Up);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "LTRIGGER", ButtonCode.KeyXButtonLTrigger);
		global.SetMemberEnumValuePrefixed(KEY_XBUTTON, "RTRIGGER", ButtonCode.KeyXButtonRTrigger);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK2, "RIGHT", ButtonCode.KeyXStick2Right);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK2, "LEFT", ButtonCode.KeyXStick2Left);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK2, "DOWN", ButtonCode.KeyXStick2Down);
		global.SetMemberEnumValuePrefixed(KEY_XSTICK2, "UP", ButtonCode.KeyXStick2Up);

		global.SetMemberEnumValuePrefixed(FCVAR, "NONE", FCvar.None);
		global.SetMemberEnumValuePrefixed(FCVAR, "UNREGISTERED", FCvar.Unregistered);
		global.SetMemberEnumValuePrefixed(FCVAR, "GAMEDLL", FCvar.GameDLL);
		global.SetMemberEnumValuePrefixed(FCVAR, "CLIENTDLL", FCvar.ClientDLL);
		global.SetMemberEnumValuePrefixed(FCVAR, "PROTECTED", FCvar.Protected);
		global.SetMemberEnumValuePrefixed(FCVAR, "SPONLY", FCvar.SingleplayerOnly);
		global.SetMemberEnumValuePrefixed(FCVAR, "ARCHIVE", FCvar.Archive);
		global.SetMemberEnumValuePrefixed(FCVAR, "NOTIFY", FCvar.Notify);
		global.SetMemberEnumValuePrefixed(FCVAR, "USERINFO", FCvar.UserInfo);
		global.SetMemberEnumValuePrefixed(FCVAR, "CHEAT", FCvar.Cheat);
		global.SetMemberEnumValuePrefixed(FCVAR, "PRINTABLEONLY", FCvar.PrintableOnly);
		global.SetMemberEnumValuePrefixed(FCVAR, "UNLOGGED", FCvar.Unlogged);
		global.SetMemberEnumValuePrefixed(FCVAR, "NEVER_AS_STRING", FCvar.NeverAsString);
		global.SetMemberEnumValuePrefixed(FCVAR, "REPLICATED", FCvar.Replicated);
		global.SetMemberEnumValuePrefixed(FCVAR, "DEMO", FCvar.Demo);
		global.SetMemberEnumValuePrefixed(FCVAR, "DONTRECORD", FCvar.DontRecord);
		global.SetMemberEnumValuePrefixed(FCVAR, "NOT_CONNECTED", FCvar.NotConnected);
		global.SetMemberEnumValuePrefixed(FCVAR, "ARCHIVE_XBOX", FCvar.ArchiveXbox);
		global.SetMemberEnumValuePrefixed(FCVAR, "SERVER_CAN_EXECUTE", FCvar.ServerCanExecute);
		global.SetMemberEnumValuePrefixed(FCVAR, "SERVER_CANNOT_QUERY", FCvar.ServerCannotQuery);
		global.SetMemberEnumValuePrefixed(FCVAR, "CLIENTCMD_CAN_EXECUTE", FCvar.ClientCmdCanExecute);
		global.SetMemberEnumValuePrefixed(FCVAR, "LUA_CLIENT", FCvar.LuaClient);
		global.SetMemberEnumValuePrefixed(FCVAR, "LUA_SERVER", FCvar.LuaServer);

		global.SetMemberEnumValuePrefixed(EF, "BONEMERGE", EntityEffects.BoneMerge);
		global.SetMemberEnumValuePrefixed(EF, "BRIGHTLIGHT", EntityEffects.BrightLight);
		global.SetMemberEnumValuePrefixed(EF, "DIMLIGHT", EntityEffects.DimLight);
		global.SetMemberEnumValuePrefixed(EF, "NOINTERP", EntityEffects.NoInterp);
		global.SetMemberEnumValuePrefixed(EF, "NOSHADOW", EntityEffects.NoShadow);
		global.SetMemberEnumValuePrefixed(EF, "NODRAW", EntityEffects.NoDraw);
		global.SetMemberEnumValuePrefixed(EF, "NORECEIVESHADOW", EntityEffects.NoReceiveShadow);
		global.SetMemberEnumValuePrefixed(EF, "NOFLASHLIGHT", EntityEffects.NoFlashlight);
		global.SetMemberEnumValuePrefixed(EF, "BONEMERGE_FASTCULL", EntityEffects.BoneMergeFastCull);
		global.SetMemberEnumValuePrefixed(EF, "ITEM_BLINK", EntityEffects.ItemBlink);
		global.SetMemberEnumValuePrefixed(EF, "PARENT_ANIMATES", EntityEffects.ParentAnimates);
		global.SetMemberEnumValuePrefixed(EF, "FOLLOWBONE", EntityEffects.FollowBone);

		global.SetMemberEnumValuesPrefixed<Activity>("ACT", shouldSetEnum: static x => x != Activity.LAST_SHARED_ACTIVITY, enumNameProducer: static x => Enum.GetName(x)!.ToUpperInvariant().AsSpan()[4..]);
		global.SetMemberEnumValue("LAST_SHARED_ACTIVITY", Activity.LAST_SHARED_ACTIVITY);

		global.SetMemberEnumValuePrefixed(BLEND, "ZERO", ShaderBlendFactor.Zero);
		global.SetMemberEnumValuePrefixed(BLEND, "ONE", ShaderBlendFactor.One);
		global.SetMemberEnumValuePrefixed(BLEND, "DST_COLOR", ShaderBlendFactor.DstColor);
		global.SetMemberEnumValuePrefixed(BLEND, "ONE_MINUS_DST_COLOR", ShaderBlendFactor.OneMinusDstColor);
		global.SetMemberEnumValuePrefixed(BLEND, "SRC_ALPHA", ShaderBlendFactor.SrcAlpha);
		global.SetMemberEnumValuePrefixed(BLEND, "ONE_MINUS_SRC_ALPHA", ShaderBlendFactor.OneMinusSrcAlpha);
		global.SetMemberEnumValuePrefixed(BLEND, "DST_ALPHA", ShaderBlendFactor.DstAlpha);
		global.SetMemberEnumValuePrefixed(BLEND, "ONE_MINUS_DST_ALPHA", ShaderBlendFactor.OneMinusDstAlpha);
		global.SetMemberEnumValuePrefixed(BLEND, "SRC_ALPHA_SATURATE", ShaderBlendFactor.SrcAlphaSat);
		global.SetMemberEnumValuePrefixed(BLEND, "SRC_COLOR", ShaderBlendFactor.SrcColor);
		global.SetMemberEnumValuePrefixed(BLEND, "ONE_MINUS_SRC_COLOR", ShaderBlendFactor.OneMinusSrcColor);

		global.SetMemberEnumValuePrefixed(BLENDFUNC, "ADD", ShaderBlendOp.Add);
		global.SetMemberEnumValuePrefixed(BLENDFUNC, "SUBTRACT", ShaderBlendOp.Subtract);
		global.SetMemberEnumValuePrefixed(BLENDFUNC, "REVERSE_SUBTRACT", ShaderBlendOp.RevSubtract);
		global.SetMemberEnumValuePrefixed(BLENDFUNC, "MIN", ShaderBlendOp.Min);
		global.SetMemberEnumValuePrefixed(BLENDFUNC, "MAX", ShaderBlendOp.Max);

		global.SetMemberDouble("BOUNDS_HITBOXES", 2.0);
		global.SetMemberDouble("BOUNDS_COLLISION", 0.0);
		global.SetMemberDouble("BOX_FRONT", 0.0);
		global.SetMemberDouble("BOX_BACK", 1.0);
		global.SetMemberDouble("BOX_RIGHT", 2.0);
		global.SetMemberDouble("BOX_LEFT", 3.0);
		global.SetMemberDouble("BOX_TOP", 4.0);
		global.SetMemberDouble("BOX_BOTTOM", 5.0);

		table = lua.CreateObject();
		lua.CreateTable();
		table.SetFromStack(-1);
		lua.Pop(1);
		table.SetMemberDouble("NONE", 0.0);
		table.SetMemberDouble("POINT", 1.0);
		table.SetMemberDouble("LINEAR", 2.0);
		table.SetMemberDouble("ANISOTROPIC", 3.0);
		global.SetMember("TEXFILTER", table);
		lua.DestroyObject(table);
#if CLIENT_DLL
		// TODO: Enum this!!
		global.SetMemberDouble("NODOCK", 0.0);
		global.SetMemberDouble("LEFT", 2.0);
		global.SetMemberDouble("TOP", 4.0);
		global.SetMemberDouble("BOTTOM", 5.0);
		global.SetMemberDouble("RIGHT", 3.0);
		global.SetMemberDouble("FILL", 1.0);

		global.SetMember("CLIENT_DLL", true);
#else
		global.SetMember("GAME_DLL", true);
#endif
	}
}

// TODO: Clean this up, in the same way we cleaned up the above.
public class LuaGameEnums : LuaUser
{
	public LuaGameEnums() => SetUsingLua(true);

	public override void InitLibraries(ILuaInterface lua) {
		ILuaObject global = lua.Global();
		ILuaObject table;
		global.SetMemberDouble("SF_PHYSPROP_MOTIONDISABLED", 8.0);
		global.SetMemberDouble("SF_PHYSPROP_PREVENT_PICKUP", 512.0);
		global.SetMemberDouble("SF_PHYSPROP_IS_GIB", 4194304.0);
		global.SetMemberDouble("SF_PHYSBOX_MOTIONDISABLED", 32768.0);
		global.SetMemberDouble("SF_PHYSBOX_ALWAYS_PICK_UP", 1048576.0);
		global.SetMemberDouble("SF_PHYSBOX_NEVER_PICK_UP", 2097152.0);
		global.SetMemberDouble("SF_PHYSBOX_NEVER_PUNT", 4194304.0);
		global.SetMemberDouble("SF_WEAPON_START_CONSTRAINED", 1.0);
		global.SetMemberDouble("SF_WEAPON_NO_PLAYER_PICKUP", 2.0);
		global.SetMemberDouble("SF_WEAPON_NO_PHYSCANNON_PUNT", 4.0);
		global.SetMemberDouble("WEAPON_PROFICIENCY_POOR", 0.0);
		global.SetMemberDouble("WEAPON_PROFICIENCY_AVERAGE", 1.0);
		global.SetMemberDouble("WEAPON_PROFICIENCY_GOOD", 2.0);
		global.SetMemberDouble("WEAPON_PROFICIENCY_VERY_GOOD", 3.0);
		global.SetMemberDouble("WEAPON_PROFICIENCY_PERFECT", 4.0);
		global.SetMemberDouble("MOVECOLLIDE_DEFAULT", 0.0);
		global.SetMemberDouble("MOVECOLLIDE_FLY_BOUNCE", 1.0);
		global.SetMemberDouble("MOVECOLLIDE_FLY_CUSTOM", 2.0);
		global.SetMemberDouble("MOVECOLLIDE_FLY_SLIDE", 3.0);
		global.SetMemberDouble("MOVECOLLIDE_COUNT", 4.0);
		global.SetMemberDouble("SOLID_NONE", 0.0);
		global.SetMemberDouble("SOLID_BSP", 1.0);
		global.SetMemberDouble("SOLID_BBOX", 2.0);
		global.SetMemberDouble("SOLID_OBB", 3.0);
		global.SetMemberDouble("SOLID_OBB_YAW", 4.0);
		global.SetMemberDouble("SOLID_CUSTOM", 5.0);
		global.SetMemberDouble("SOLID_VPHYSICS", 6.0);
		global.SetMemberDouble("PLAYER_IDLE", 0.0);
		global.SetMemberDouble("PLAYER_WALK", 1.0);
		global.SetMemberDouble("PLAYER_JUMP", 2.0);
		global.SetMemberDouble("PLAYER_SUPERJUMP", 3.0);
		global.SetMemberDouble("PLAYER_DIE", 4.0);
		global.SetMemberDouble("PLAYER_ATTACK1", 5.0);
		global.SetMemberDouble("PLAYER_IN_VEHICLE", 6.0);
		global.SetMemberDouble("PLAYER_RELOAD", 7.0);
		global.SetMemberDouble("PLAYER_START_AIMING", 8.0);
		global.SetMemberDouble("PLAYER_LEAVE_AIMING", 9.0);
		global.SetMemberDouble("OBS_MODE_NONE", 0.0);
		global.SetMemberDouble("OBS_MODE_DEATHCAM", 1.0);
		global.SetMemberDouble("OBS_MODE_FREEZECAM", 2.0);
		global.SetMemberDouble("OBS_MODE_FIXED", 3.0);
		global.SetMemberDouble("OBS_MODE_IN_EYE", 4.0);
		global.SetMemberDouble("OBS_MODE_CHASE", 5.0);
		global.SetMemberDouble("OBS_MODE_ROAMING", 6.0);
		global.SetMemberDouble("MOVETYPE_NONE", 0.0);
		global.SetMemberDouble("MOVETYPE_ISOMETRIC", 1.0);
		global.SetMemberDouble("MOVETYPE_WALK", 2.0);
		global.SetMemberDouble("MOVETYPE_STEP", 3.0);
		global.SetMemberDouble("MOVETYPE_FLY", 4.0);
		global.SetMemberDouble("MOVETYPE_FLYGRAVITY", 5.0);
		global.SetMemberDouble("MOVETYPE_VPHYSICS", 6.0);
		global.SetMemberDouble("MOVETYPE_PUSH", 7.0);
		global.SetMemberDouble("MOVETYPE_NOCLIP", 8.0);
		global.SetMemberDouble("MOVETYPE_LADDER", 9.0);
		global.SetMemberDouble("MOVETYPE_OBSERVER", 10.0);
		global.SetMemberDouble("MOVETYPE_CUSTOM", 11.0);
		global.SetMemberDouble("CONTENTS_EMPTY", 0.0);
		global.SetMemberDouble("CONTENTS_SOLID", 1.0);
		global.SetMemberDouble("CONTENTS_WINDOW", 2.0);
		global.SetMemberDouble("CONTENTS_AUX", 4.0);
		global.SetMemberDouble("CONTENTS_GRATE", 8.0);
		global.SetMemberDouble("CONTENTS_SLIME", 16.0);
		global.SetMemberDouble("CONTENTS_WATER", 32.0);
		global.SetMemberDouble("CONTENTS_BLOCKLOS", 64.0);
		global.SetMemberDouble("CONTENTS_OPAQUE", 128.0);
		global.SetMemberDouble("LAST_VISIBLE_CONTENTS", 128.0);
		global.SetMemberDouble("ALL_VISIBLE_CONTENTS", 255.0);
		global.SetMemberDouble("CONTENTS_TESTFOGVOLUME", 256.0);
		global.SetMemberDouble("CONTENTS_TEAM1", 2048.0);
		global.SetMemberDouble("CONTENTS_TEAM2", 4096.0);
		global.SetMemberDouble("CONTENTS_TEAM3", 1024.0);
		global.SetMemberDouble("CONTENTS_TEAM4", 512.0);
		global.SetMemberDouble("CONTENTS_IGNORE_NODRAW_OPAQUE", 8192.0);
		global.SetMemberDouble("CONTENTS_MOVEABLE", 16384.0);
		global.SetMemberDouble("CONTENTS_AREAPORTAL", 32768.0);
		global.SetMemberDouble("CONTENTS_PLAYERCLIP", 65536.0);
		global.SetMemberDouble("CONTENTS_MONSTERCLIP", 131072.0);
		global.SetMemberDouble("CONTENTS_CURRENT_0", 262144.0);
		global.SetMemberDouble("CONTENTS_CURRENT_90", 524288.0);
		global.SetMemberDouble("CONTENTS_CURRENT_180", 1048576.0);
		global.SetMemberDouble("CONTENTS_CURRENT_270", 2097152.0);
		global.SetMemberDouble("CONTENTS_CURRENT_UP", 4194304.0);
		global.SetMemberDouble("CONTENTS_CURRENT_DOWN", 8388608.0);
		global.SetMemberDouble("CONTENTS_ORIGIN", 16777216.0);
		global.SetMemberDouble("CONTENTS_MONSTER", 33554432.0);
		global.SetMemberDouble("CONTENTS_DEBRIS", 67108864.0);
		global.SetMemberDouble("CONTENTS_DETAIL", 134217728.0);
		global.SetMemberDouble("CONTENTS_TRANSLUCENT", 268435456.0);
		global.SetMemberDouble("CONTENTS_LADDER", 536870912.0);
		global.SetMemberDouble("CONTENTS_HITBOX", 1073741824.0);
		global.SetMemberDouble("SURF_LIGHT", 1.0);
		global.SetMemberDouble("SURF_SKY2D", 2.0);
		global.SetMemberDouble("SURF_SKY", 4.0);
		global.SetMemberDouble("SURF_WARP", 8.0);
		global.SetMemberDouble("SURF_TRANS", 16.0);
		global.SetMemberDouble("SURF_NOPORTAL", 32.0);
		global.SetMemberDouble("SURF_TRIGGER", 64.0);
		global.SetMemberDouble("SURF_NODRAW", 128.0);
		global.SetMemberDouble("SURF_HINT", 256.0);
		global.SetMemberDouble("SURF_SKIP", 512.0);
		global.SetMemberDouble("SURF_NOLIGHT", 1024.0);
		global.SetMemberDouble("SURF_BUMPLIGHT", 2048.0);
		global.SetMemberDouble("SURF_NOSHADOWS", 4096.0);
		global.SetMemberDouble("SURF_NODECALS", 8192.0);
		global.SetMemberDouble("SURF_NOCHOP", 16384.0);
		global.SetMemberDouble("SURF_HITBOX", 32768.0);
		global.SetMemberDouble("DISPSURF_SURFACE", 1.0);
		global.SetMemberDouble("DISPSURF_WALKABLE", 2.0);
		global.SetMemberDouble("DISPSURF_BUILDABLE", 4.0);
		global.SetMemberDouble("DISPSURF_SURFPROP1", 8.0);
		global.SetMemberDouble("DISPSURF_SURFPROP2", 16.0);
		global.SetMemberDouble("MASK_ALL", 4294967295.0);
		global.SetMemberDouble("MASK_SOLID", 33570827.0);
		global.SetMemberDouble("MASK_PLAYERSOLID", 33636363.0);
		global.SetMemberDouble("MASK_NPCSOLID", 33701899.0);
		global.SetMemberDouble("MASK_WATER", 16432.0);
		global.SetMemberDouble("MASK_OPAQUE", 16513.0);
		global.SetMemberDouble("MASK_OPAQUE_AND_NPCS", 33570945.0);
		global.SetMemberDouble("MASK_BLOCKLOS", 16449.0);
		global.SetMemberDouble("MASK_BLOCKLOS_AND_NPCS", 33570881.0);
		global.SetMemberDouble("MASK_VISIBLE", 24705.0);
		global.SetMemberDouble("MASK_VISIBLE_AND_NPCS", 33579137.0);
		global.SetMemberDouble("MASK_SHOT", 1174421507.0);
		global.SetMemberDouble("MASK_SHOT_HULL", 100679691.0);
		global.SetMemberDouble("MASK_SHOT_PORTAL", 33570819.0);
		global.SetMemberDouble("MASK_SOLID_BRUSHONLY", 16395.0);
		global.SetMemberDouble("MASK_PLAYERSOLID_BRUSHONLY", 81931.0);
		global.SetMemberDouble("MASK_NPCSOLID_BRUSHONLY", 147467.0);
		global.SetMemberDouble("MASK_NPCWORLDSTATIC", 131083.0);
		global.SetMemberDouble("MASK_SPLITAREAPORTAL", 48.0);
		global.SetMemberDouble("MASK_CURRENT", 16515072.0);
		global.SetMemberDouble("MASK_DEADSOLID", 65547.0);
		global.SetMemberDouble("IN_ATTACK", 1.0);
		global.SetMemberDouble("IN_JUMP", 2.0);
		global.SetMemberDouble("IN_DUCK", 4.0);
		global.SetMemberDouble("IN_FORWARD", 8.0);
		global.SetMemberDouble("IN_BACK", 16.0);
		global.SetMemberDouble("IN_USE", 32.0);
		global.SetMemberDouble("IN_CANCEL", 64.0);
		global.SetMemberDouble("IN_LEFT", 128.0);
		global.SetMemberDouble("IN_RIGHT", 256.0);
		global.SetMemberDouble("IN_MOVELEFT", 512.0);
		global.SetMemberDouble("IN_MOVERIGHT", 1024.0);
		global.SetMemberDouble("IN_ATTACK2", 2048.0);
		global.SetMemberDouble("IN_RUN", 4096.0);
		global.SetMemberDouble("IN_RELOAD", 8192.0);
		global.SetMemberDouble("IN_ALT1", 16384.0);
		global.SetMemberDouble("IN_ALT2", 32768.0);
		global.SetMemberDouble("IN_SCORE", 65536.0);
		global.SetMemberDouble("IN_SPEED", 131072.0);
		global.SetMemberDouble("IN_WALK", 262144.0);
		global.SetMemberDouble("IN_ZOOM", 524288.0);
		global.SetMemberDouble("IN_WEAPON1", 1048576.0);
		global.SetMemberDouble("IN_WEAPON2", 2097152.0);
		global.SetMemberDouble("IN_BULLRUSH", 4194304.0);
		global.SetMemberDouble("IN_GRENADE1", 8388608.0);
		global.SetMemberDouble("IN_GRENADE2", 16777216.0);
		global.SetMemberDouble("PLAYER_IDLE", 0.0);
		global.SetMemberDouble("PLAYER_WALK", 1.0);
		global.SetMemberDouble("PLAYER_JUMP", 2.0);
		global.SetMemberDouble("PLAYER_SUPERJUMP", 3.0);
		global.SetMemberDouble("PLAYER_DIE", 4.0);
		global.SetMemberDouble("PLAYER_ATTACK1", 5.0);
		global.SetMemberDouble("PLAYER_IN_VEHICLE", 6.0);
		global.SetMemberDouble("PLAYER_RELOAD", 7.0);
		global.SetMemberDouble("PLAYER_START_AIMING", 8.0);
		global.SetMemberDouble("PLAYER_LEAVE_AIMING", 9.0);
		global.SetMemberDouble("HITGROUP_GENERIC", 0.0);
		global.SetMemberDouble("HITGROUP_HEAD", 1.0);
		global.SetMemberDouble("HITGROUP_CHEST", 2.0);
		global.SetMemberDouble("HITGROUP_STOMACH", 3.0);
		global.SetMemberDouble("HITGROUP_LEFTARM", 4.0);
		global.SetMemberDouble("HITGROUP_RIGHTARM", 5.0);
		global.SetMemberDouble("HITGROUP_LEFTLEG", 6.0);
		global.SetMemberDouble("HITGROUP_RIGHTLEG", 7.0);
		global.SetMemberDouble("HITGROUP_GEAR", 10.0);
		global.SetMemberDouble("DMG_GENERIC", 0.0);
		global.SetMemberDouble("DMG_CRUSH", 1.0);
		global.SetMemberDouble("DMG_BULLET", 2.0);
		global.SetMemberDouble("DMG_SLASH", 4.0);
		global.SetMemberDouble("DMG_BURN", 8.0);
		global.SetMemberDouble("DMG_VEHICLE", 16.0);
		global.SetMemberDouble("DMG_FALL", 32.0);
		global.SetMemberDouble("DMG_BLAST", 64.0);
		global.SetMemberDouble("DMG_CLUB", 128.0);
		global.SetMemberDouble("DMG_SHOCK", 256.0);
		global.SetMemberDouble("DMG_SONIC", 512.0);
		global.SetMemberDouble("DMG_ENERGYBEAM", 1024.0);
		global.SetMemberDouble("DMG_PREVENT_PHYSICS_FORCE", 2048.0);
		global.SetMemberDouble("DMG_NEVERGIB", 4096.0);
		global.SetMemberDouble("DMG_ALWAYSGIB", 8192.0);
		global.SetMemberDouble("DMG_DROWN", 16384.0);
		global.SetMemberDouble("DMG_PARALYZE", 32768.0);
		global.SetMemberDouble("DMG_NERVEGAS", 65536.0);
		global.SetMemberDouble("DMG_POISON", 131072.0);
		global.SetMemberDouble("DMG_RADIATION", 262144.0);
		global.SetMemberDouble("DMG_DROWNRECOVER", 524288.0);
		global.SetMemberDouble("DMG_ACID", 1048576.0);
		global.SetMemberDouble("DMG_SLOWBURN", 2097152.0);
		global.SetMemberDouble("DMG_REMOVENORAGDOLL", 4194304.0);
		global.SetMemberDouble("DMG_PHYSGUN", 8388608.0);
		global.SetMemberDouble("DMG_PLASMA", 16777216.0);
		global.SetMemberDouble("DMG_AIRBOAT", 33554432.0);
		global.SetMemberDouble("DMG_DISSOLVE", 67108864.0);
		global.SetMemberDouble("DMG_BLAST_SURFACE", 134217728.0);
		global.SetMemberDouble("DMG_DIRECT", 268435456.0);
		global.SetMemberDouble("DMG_BUCKSHOT", 536870912.0);
		global.SetMemberDouble("DMG_SNIPER", 1073741824.0);
		global.SetMemberDouble("DMG_MISSILEDEFENSE", 2147483648.0);
		global.SetMemberDouble("COLLISION_GROUP_NONE", 0.0);
		global.SetMemberDouble("COLLISION_GROUP_DEBRIS", 1.0);
		global.SetMemberDouble("COLLISION_GROUP_DEBRIS_TRIGGER", 2.0);
		global.SetMemberDouble("COLLISION_GROUP_INTERACTIVE_DEBRIS", 3.0);
		global.SetMemberDouble("COLLISION_GROUP_INTERACTIVE", 4.0);
		global.SetMemberDouble("COLLISION_GROUP_PLAYER", 5.0);
		global.SetMemberDouble("COLLISION_GROUP_BREAKABLE_GLASS", 6.0);
		global.SetMemberDouble("COLLISION_GROUP_VEHICLE", 7.0);
		global.SetMemberDouble("COLLISION_GROUP_PLAYER_MOVEMENT", 8.0);
		global.SetMemberDouble("COLLISION_GROUP_NPC", 9.0);
		global.SetMemberDouble("COLLISION_GROUP_IN_VEHICLE", 10.0);
		global.SetMemberDouble("COLLISION_GROUP_WEAPON", 11.0);
		global.SetMemberDouble("COLLISION_GROUP_VEHICLE_CLIP", 12.0);
		global.SetMemberDouble("COLLISION_GROUP_PROJECTILE", 13.0);
		global.SetMemberDouble("COLLISION_GROUP_DOOR_BLOCKER", 14.0);
		global.SetMemberDouble("COLLISION_GROUP_PASSABLE_DOOR", 15.0);
		global.SetMemberDouble("COLLISION_GROUP_DISSOLVING", 16.0);
		global.SetMemberDouble("COLLISION_GROUP_PUSHAWAY", 17.0);
		global.SetMemberDouble("COLLISION_GROUP_NPC_ACTOR", 18.0);
		global.SetMemberDouble("COLLISION_GROUP_NPC_SCRIPTED", 19.0);
		global.SetMemberDouble("COLLISION_GROUP_WORLD", 20.0);
		global.SetMemberDouble("LAST_SHARED_COLLISION_GROUP", 21.0);
		global.SetMemberDouble("COLLISION_GROUP_HL2_SPIT", 22.0);
		global.SetMemberDouble("FVPHYSICS_DMG_SLICE", 1.0);
		global.SetMemberDouble("FVPHYSICS_CONSTRAINT_STATIC", 2.0);
		global.SetMemberDouble("FVPHYSICS_PLAYER_HELD", 4.0);
		global.SetMemberDouble("FVPHYSICS_PART_OF_RAGDOLL", 8.0);
		global.SetMemberDouble("FVPHYSICS_MULTIOBJECT_ENTITY", 16.0);
		global.SetMemberDouble("FVPHYSICS_HEAVY_OBJECT", 32.0);
		global.SetMemberDouble("FVPHYSICS_PENETRATING", 64.0);
		global.SetMemberDouble("FVPHYSICS_NO_PLAYER_PICKUP", 128.0);
		global.SetMemberDouble("FVPHYSICS_WAS_THROWN", 256.0);
		global.SetMemberDouble("FVPHYSICS_DMG_DISSOLVE", 512.0);
		global.SetMemberDouble("FVPHYSICS_NO_IMPACT_DMG", 1024.0);
		global.SetMemberDouble("FVPHYSICS_NO_NPC_IMPACT_DMG", 2048.0);
		global.SetMemberDouble("FVPHYSICS_NO_SELF_COLLISIONS", 32768.0);
		global.SetMemberDouble("STEPSOUNDTIME_NORMAL", 0.0);
		global.SetMemberDouble("STEPSOUNDTIME_ON_LADDER", 1.0);
		global.SetMemberDouble("STEPSOUNDTIME_WATER_KNEE", 2.0);
		global.SetMemberDouble("STEPSOUNDTIME_WATER_FOOT", 3.0);
		global.SetMemberDouble("PATTACH_ABSORIGIN", 0.0);
		global.SetMemberDouble("PATTACH_ABSORIGIN_FOLLOW", 1.0);
		global.SetMemberDouble("PATTACH_CUSTOMORIGIN", 2.0);
		global.SetMemberDouble("PATTACH_POINT", 3.0);
		global.SetMemberDouble("PATTACH_POINT_FOLLOW", 4.0);
		global.SetMemberDouble("PATTACH_WORLDORIGIN", 5.0);
		global.SetMemberDouble("DONT_BLEED", -1.0);
		global.SetMemberDouble("BLOOD_COLOR_RED", 0.0);
		global.SetMemberDouble("BLOOD_COLOR_YELLOW", 1.0);
		global.SetMemberDouble("BLOOD_COLOR_GREEN", 2.0);
		global.SetMemberDouble("BLOOD_COLOR_MECH", 3.0);
		global.SetMemberDouble("BLOOD_COLOR_ANTLION", 4.0);
		global.SetMemberDouble("BLOOD_COLOR_ZOMBIE", 5.0);
		global.SetMemberDouble("BLOOD_COLOR_ANTLION_WORKER", 6.0);
		global.SetMemberDouble("BLOOD_COLOR_RED", 0.0);
		global.SetMemberDouble("PLAYERANIMEVENT_ATTACK_PRIMARY", 0.0);
		global.SetMemberDouble("PLAYERANIMEVENT_ATTACK_SECONDARY", 1.0);
		global.SetMemberDouble("PLAYERANIMEVENT_ATTACK_GRENADE", 2.0);
		global.SetMemberDouble("PLAYERANIMEVENT_RELOAD", 3.0);
		global.SetMemberDouble("PLAYERANIMEVENT_RELOAD_LOOP", 4.0);
		global.SetMemberDouble("PLAYERANIMEVENT_RELOAD_END", 5.0);
		global.SetMemberDouble("PLAYERANIMEVENT_JUMP", 6.0);
		global.SetMemberDouble("PLAYERANIMEVENT_SWIM", 7.0);
		global.SetMemberDouble("PLAYERANIMEVENT_DIE", 8.0);
		global.SetMemberDouble("PLAYERANIMEVENT_FLINCH_CHEST", 9.0);
		global.SetMemberDouble("PLAYERANIMEVENT_FLINCH_HEAD", 10.0);
		global.SetMemberDouble("PLAYERANIMEVENT_FLINCH_LEFTARM", 11.0);
		global.SetMemberDouble("PLAYERANIMEVENT_FLINCH_RIGHTARM", 12.0);
		global.SetMemberDouble("PLAYERANIMEVENT_FLINCH_LEFTLEG", 13.0);
		global.SetMemberDouble("PLAYERANIMEVENT_FLINCH_RIGHTLEG", 14.0);
		global.SetMemberDouble("PLAYERANIMEVENT_DOUBLEJUMP", 15.0);
		global.SetMemberDouble("PLAYERANIMEVENT_CANCEL", 16.0);
		global.SetMemberDouble("PLAYERANIMEVENT_CANCEL_RELOAD", 23.0);
		global.SetMemberDouble("PLAYERANIMEVENT_SPAWN", 17.0);
		global.SetMemberDouble("PLAYERANIMEVENT_SNAP_YAW", 18.0);
		global.SetMemberDouble("PLAYERANIMEVENT_CUSTOM", 19.0);
		global.SetMemberDouble("PLAYERANIMEVENT_CUSTOM_GESTURE", 20.0);
		global.SetMemberDouble("PLAYERANIMEVENT_CUSTOM_SEQUENCE", 21.0);
		global.SetMemberDouble("PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE", 22.0);
		global.SetMemberDouble("GESTURE_SLOT_ATTACK_AND_RELOAD", 0.0);
		global.SetMemberDouble("GESTURE_SLOT_GRENADE", 1.0);
		global.SetMemberDouble("GESTURE_SLOT_JUMP", 2.0);
		global.SetMemberDouble("GESTURE_SLOT_SWIM", 3.0);
		global.SetMemberDouble("GESTURE_SLOT_FLINCH", 4.0);
		global.SetMemberDouble("GESTURE_SLOT_VCD", 5.0);
		global.SetMemberDouble("GESTURE_SLOT_CUSTOM", 6.0);
		global.SetMemberDouble("kRenderFxNone", 0.0);
		global.SetMemberDouble("kRenderFxPulseSlow", 1.0);
		global.SetMemberDouble("kRenderFxPulseFast", 2.0);
		global.SetMemberDouble("kRenderFxPulseSlowWide", 3.0);
		global.SetMemberDouble("kRenderFxPulseFastWide", 4.0);
		global.SetMemberDouble("kRenderFxFadeSlow", 5.0);
		global.SetMemberDouble("kRenderFxFadeFast", 6.0);
		global.SetMemberDouble("kRenderFxSolidSlow", 7.0);
		global.SetMemberDouble("kRenderFxSolidFast", 8.0);
		global.SetMemberDouble("kRenderFxStrobeSlow", 9.0);
		global.SetMemberDouble("kRenderFxStrobeFast", 10.0);
		global.SetMemberDouble("kRenderFxStrobeFaster", 11.0);
		global.SetMemberDouble("kRenderFxFlickerSlow", 12.0);
		global.SetMemberDouble("kRenderFxFlickerFast", 13.0);
		global.SetMemberDouble("kRenderFxNoDissipation", 14.0);
		global.SetMemberDouble("kRenderFxDistort", 15.0);
		global.SetMemberDouble("kRenderFxHologram", 16.0);
		global.SetMemberDouble("kRenderFxExplode", 17.0);
		global.SetMemberDouble("kRenderFxGlowShell", 18.0);
		global.SetMemberDouble("kRenderFxClampMinScale", 19.0);
		global.SetMemberDouble("kRenderFxEnvRain", 20.0);
		global.SetMemberDouble("kRenderFxEnvSnow", 21.0);
		global.SetMemberDouble("kRenderFxSpotlight", 22.0);
		global.SetMemberDouble("kRenderFxRagdoll", 23.0);
		global.SetMemberDouble("kRenderFxPulseFastWider", 24.0);
		global.SetMemberDouble("MAT_ANTLION", 65.0);
		global.SetMemberDouble("MAT_BLOODYFLESH", 66.0);
		global.SetMemberDouble("MAT_CONCRETE", 67.0);
		global.SetMemberDouble("MAT_DIRT", 68.0);
		global.SetMemberDouble("MAT_EGGSHELL", 69.0);
		global.SetMemberDouble("MAT_FLESH", 70.0);
		global.SetMemberDouble("MAT_GRATE", 71.0);
		global.SetMemberDouble("MAT_ALIENFLESH", 72.0);
		global.SetMemberDouble("MAT_CLIP", 73.0);
		global.SetMemberDouble("MAT_SNOW", 74.0);
		global.SetMemberDouble("MAT_PLASTIC", 76.0);
		global.SetMemberDouble("MAT_METAL", 77.0);
		global.SetMemberDouble("MAT_SAND", 78.0);
		global.SetMemberDouble("MAT_FOLIAGE", 79.0);
		global.SetMemberDouble("MAT_COMPUTER", 80.0);
		global.SetMemberDouble("MAT_SLOSH", 83.0);
		global.SetMemberDouble("MAT_TILE", 84.0);
		global.SetMemberDouble("MAT_GRASS", 85.0);
		global.SetMemberDouble("MAT_VENT", 86.0);
		global.SetMemberDouble("MAT_WOOD", 87.0);
		global.SetMemberDouble("MAT_DEFAULT", 88.0);
		global.SetMemberDouble("MAT_GLASS", 89.0);
		global.SetMemberDouble("MAT_WARPSHIELD", 90.0);
		global.SetMemberDouble("EFL_KILLME", 1.0);
		global.SetMemberDouble("EFL_DORMANT", 2.0);
		global.SetMemberDouble("EFL_NOCLIP_ACTIVE", 4.0);
		global.SetMemberDouble("EFL_SETTING_UP_BONES", 8.0);
		global.SetMemberDouble("EFL_KEEP_ON_RECREATE_ENTITIES", 16.0);
		global.SetMemberDouble("EFL_HAS_PLAYER_CHILD", 65536.0);
		global.SetMemberDouble("EFL_DIRTY_SHADOWUPDATE", 32.0);
		global.SetMemberDouble("EFL_NOTIFY", 64.0);
		global.SetMemberDouble("EFL_FORCE_CHECK_TRANSMIT", 128.0);
		global.SetMemberDouble("EFL_BOT_FROZEN", 256.0);
		global.SetMemberDouble("EFL_SERVER_ONLY", 512.0);
		global.SetMemberDouble("EFL_NO_AUTO_EDICT_ATTACH", 1024.0);
		global.SetMemberDouble("EFL_DIRTY_ABSTRANSFORM", 2048.0);
		global.SetMemberDouble("EFL_DIRTY_ABSVELOCITY", 4096.0);
		global.SetMemberDouble("EFL_DIRTY_ABSANGVELOCITY", 8192.0);
		global.SetMemberDouble("EFL_DIRTY_SURROUNDING_COLLISION_BOUNDS", 16384.0);
		global.SetMemberDouble("EFL_DIRTY_SPATIAL_PARTITION", 32768.0);
		global.SetMemberDouble("EFL_IN_SKYBOX", 131072.0);
		global.SetMemberDouble("EFL_USE_PARTITION_WHEN_NOT_SOLID", 262144.0);
		global.SetMemberDouble("EFL_TOUCHING_FLUID", 524288.0);
		global.SetMemberDouble("EFL_IS_BEING_LIFTED_BY_BARNACLE", 1048576.0);
		global.SetMemberDouble("EFL_NO_ROTORWASH_PUSH", 2097152.0);
		global.SetMemberDouble("EFL_NO_THINK_FUNCTION", 4194304.0);
		global.SetMemberDouble("EFL_NO_GAME_PHYSICS_SIMULATION", 8388608.0);
		global.SetMemberDouble("EFL_CHECK_UNTOUCH", 16777216.0);
		global.SetMemberDouble("EFL_DONTBLOCKLOS", 33554432.0);
		global.SetMemberDouble("EFL_DONTWALKON", 67108864.0);
		global.SetMemberDouble("EFL_NO_DISSOLVE", 134217728.0);
		global.SetMemberDouble("EFL_NO_MEGAPHYSCANNON_RAGDOLL", 268435456.0);
		global.SetMemberDouble("EFL_NO_WATER_VELOCITY_CHANGE", 536870912.0);
		global.SetMemberDouble("EFL_NO_PHYSCANNON_INTERACTION", 1073741824.0);
		global.SetMemberDouble("EFL_NO_DAMAGE_FORCES", -2147483648.0);
		global.SetMemberDouble("FL_ONGROUND", 1.0);
		global.SetMemberDouble("FL_DUCKING", 2.0);
		global.SetMemberDouble("FL_ANIMDUCKING", 4.0);
		global.SetMemberDouble("FL_WATERJUMP", 8.0);
		global.SetMemberDouble("FL_ONTRAIN", 16.0);
		global.SetMemberDouble("FL_INRAIN", 32.0);
		global.SetMemberDouble("FL_FROZEN", 64.0);
		global.SetMemberDouble("FL_ATCONTROLS", 128.0);
		global.SetMemberDouble("FL_CLIENT", 256.0);
		global.SetMemberDouble("FL_FAKECLIENT", 512.0);
		global.SetMemberDouble("FL_INWATER", 1024.0);
		global.SetMemberDouble("FL_FLY", 2048.0);
		global.SetMemberDouble("FL_SWIM", 4096.0);
		global.SetMemberDouble("FL_CONVEYOR", 8192.0);
		global.SetMemberDouble("FL_NPC", 16384.0);
		global.SetMemberDouble("FL_GODMODE", 32768.0);
		global.SetMemberDouble("FL_NOTARGET", 65536.0);
		global.SetMemberDouble("FL_AIMTARGET", 131072.0);
		global.SetMemberDouble("FL_PARTIALGROUND", 262144.0);
		global.SetMemberDouble("FL_STATICPROP", 524288.0);
		global.SetMemberDouble("FL_GRAPHED", 1048576.0);
		global.SetMemberDouble("FL_GRENADE", 2097152.0);
		global.SetMemberDouble("FL_STEPMOVEMENT", 4194304.0);
		global.SetMemberDouble("FL_DONTTOUCH", 8388608.0);
		global.SetMemberDouble("FL_BASEVELOCITY", 16777216.0);
		global.SetMemberDouble("FL_WORLDBRUSH", 33554432.0);
		global.SetMemberDouble("FL_OBJECT", 67108864.0);
		global.SetMemberDouble("FL_KILLME", 134217728.0);
		global.SetMemberDouble("FL_ONFIRE", 268435456.0);
		global.SetMemberDouble("FL_DISSOLVING", 536870912.0);
		global.SetMemberDouble("FL_TRANSRAGDOLL", 1073741824.0);
		global.SetMemberDouble("FL_UNBLOCKABLE_BY_PLAYER", -2147483648.0);
		global.SetMemberDouble("SIGNONSTATE_NONE", 0.0);
		global.SetMemberDouble("SIGNONSTATE_CHALLENGE", 1.0);
		global.SetMemberDouble("SIGNONSTATE_CONNECTED", 2.0);
		global.SetMemberDouble("SIGNONSTATE_NEW", 3.0);
		global.SetMemberDouble("SIGNONSTATE_PRESPAWN", 4.0);
		global.SetMemberDouble("SIGNONSTATE_SPAWN", 5.0);
		global.SetMemberDouble("SIGNONSTATE_FULL", 6.0);
		global.SetMemberDouble("SIGNONSTATE_CHANGELEVEL", 7.0);
		global.SetMemberDouble("FSASYNC_ERR_NOT_MINE", -8.0);
		global.SetMemberDouble("FSASYNC_ERR_RETRY_LATER", -7.0);
		global.SetMemberDouble("FSASYNC_ERR_ALIGNMENT", -6.0);
		global.SetMemberDouble("FSASYNC_ERR_FAILURE", -5.0);
		global.SetMemberDouble("FSASYNC_ERR_READING", -4.0);
		global.SetMemberDouble("FSASYNC_ERR_NOMEMORY", -3.0);
		global.SetMemberDouble("FSASYNC_ERR_UNKNOWNID", -2.0);
		global.SetMemberDouble("FSASYNC_ERR_FILEOPEN", -1.0);
		global.SetMemberDouble("FSASYNC_OK", 0.0);
		global.SetMemberDouble("FSASYNC_STATUS_PENDING", 1.0);
		global.SetMemberDouble("FSASYNC_STATUS_INPROGRESS", 2.0);
		global.SetMemberDouble("FSASYNC_STATUS_ABORTED", 3.0);
		global.SetMemberDouble("FSASYNC_STATUS_UNSERVICED", 4.0);
		global.SetMemberDouble("RENDERGROUP_OPAQUE_HUGE", 1.0);
		global.SetMemberDouble("RENDERGROUP_TRANSLUCENT", 8.0);
		global.SetMemberDouble("RENDERGROUP_OPAQUE", 7.0);
		global.SetMemberDouble("RENDERGROUP_BOTH", 9.0);
		global.SetMemberDouble("RENDERGROUP_VIEWMODEL", 10.0);
		global.SetMemberDouble("RENDERGROUP_VIEWMODEL_TRANSLUCENT", 11.0);
		global.SetMemberDouble("RENDERGROUP_OPAQUE_BRUSH", 12.0);
		global.SetMemberDouble("RENDERGROUP_OTHER", 13.0);
		global.SetMemberDouble("RENDERGROUP_STATIC", 6.0);
		global.SetMemberDouble("RENDERGROUP_STATIC_HUGE", 0.0);
		global.SetMemberDouble("SIM_NOTHING", 0.0);
		global.SetMemberDouble("SIM_LOCAL_ACCELERATION", 1.0);
		global.SetMemberDouble("SIM_LOCAL_FORCE", 2.0);
		global.SetMemberDouble("SIM_GLOBAL_ACCELERATION", 3.0);
		global.SetMemberDouble("SIM_GLOBAL_FORCE", 4.0);
		global.SetMemberDouble("RENDERMODE_NORMAL", 0.0);
		global.SetMemberDouble("RENDERMODE_TRANSCOLOR", 1.0);
		global.SetMemberDouble("RENDERMODE_TRANSTEXTURE", 2.0);
		global.SetMemberDouble("RENDERMODE_GLOW", 3.0);
		global.SetMemberDouble("RENDERMODE_TRANSALPHA", 4.0);
		global.SetMemberDouble("RENDERMODE_TRANSADD", 5.0);
		global.SetMemberDouble("RENDERMODE_ENVIROMENTAL", 6.0);
		global.SetMemberDouble("RENDERMODE_TRANSADDFRAMEBLEND", 7.0);
		global.SetMemberDouble("RENDERMODE_TRANSALPHADD", 8.0);
		global.SetMemberDouble("RENDERMODE_WORLDGLOW", 9.0);
		global.SetMemberDouble("RENDERMODE_NONE", 10.0);
		global.SetMemberDouble("BONE_CALCULATE_MASK", 31.0);
		global.SetMemberDouble("BONE_PHYSICALLY_SIMULATED", 1.0);
		global.SetMemberDouble("BONE_PHYSICS_PROCEDURAL", 2.0);
		global.SetMemberDouble("BONE_ALWAYS_PROCEDURAL", 4.0);
		global.SetMemberDouble("BONE_SCREEN_ALIGN_SPHERE", 8.0);
		global.SetMemberDouble("BONE_SCREEN_ALIGN_CYLINDER", 16.0);
		global.SetMemberDouble("BONE_USED_MASK", 524032.0);
		global.SetMemberDouble("BONE_USED_BY_ANYTHING", 524032.0);
		global.SetMemberDouble("BONE_USED_BY_HITBOX", 256.0);
		global.SetMemberDouble("BONE_USED_BY_ATTACHMENT", 512.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_MASK", 261120.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD0", 1024.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD1", 2048.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD2", 4096.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD3", 8192.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD4", 16384.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD5", 32768.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD6", 65536.0);
		global.SetMemberDouble("BONE_USED_BY_VERTEX_LOD7", 131072.0);
		global.SetMemberDouble("BONE_USED_BY_BONE_MERGE", 262144.0);
		global.SetMemberDouble("CONTINUOUS_USE", 0.0);
		global.SetMemberDouble("ONOFF_USE", 1.0);
		global.SetMemberDouble("DIRECTIONAL_USE", 2.0);
		global.SetMemberDouble("SIMPLE_USE", 3.0);
		global.SetMemberDouble("USE_OFF", 0.0);
		global.SetMemberDouble("USE_ON", 1.0);
		global.SetMemberDouble("USE_SET", 2.0);
		global.SetMemberDouble("USE_TOGGLE", 3.0);
		global.SetMemberDouble("TRANSMIT_ALWAYS", 0.0);
		global.SetMemberDouble("TRANSMIT_NEVER", 1.0);
		global.SetMemberDouble("TRANSMIT_PVS", 2.0);
		global.SetMemberDouble("TEXT_ALIGN_LEFT", 0.0);
		global.SetMemberDouble("TEXT_ALIGN_CENTER", 1.0);
		global.SetMemberDouble("TEXT_ALIGN_RIGHT", 2.0);
		global.SetMemberDouble("TEXT_ALIGN_TOP", 3.0);
		global.SetMemberDouble("TEXT_ALIGN_BOTTOM", 4.0);
		global.SetMemberDouble("TEAM_CONNECTING", 0.0);
		global.SetMemberDouble("TEAM_UNASSIGNED", 1001.0);
		global.SetMemberDouble("TEAM_SPECTATOR", 1002.0);
		global.SetMemberDouble("MAX_EDICT_BITS", 13.0);
		global.SetMemberDouble("MAX_PLAYER_BITS", Math.Log2(gpGlobals.MaxClients) + 1);
		global.SetMemberDouble("GMOD_MAXDTVARS", 32.0);
		global.SetMemberDouble("HUD_PRINTNOTIFY", 1.0);
		global.SetMemberDouble("HUD_PRINTCONSOLE", 2.0);
		global.SetMemberDouble("HUD_PRINTTALK", 3.0);
		global.SetMemberDouble("HUD_PRINTCENTER", 4.0);
		global.SetMemberDouble("CHAN_REPLACE", -1.0);
		global.SetMemberDouble("CHAN_AUTO", 0.0);
		global.SetMemberDouble("CHAN_WEAPON", 1.0);
		global.SetMemberDouble("CHAN_VOICE", 2.0);
		global.SetMemberDouble("CHAN_ITEM", 3.0);
		global.SetMemberDouble("CHAN_BODY", 4.0);
		global.SetMemberDouble("CHAN_STREAM", 5.0);
		global.SetMemberDouble("CHAN_STATIC", 6.0);
		global.SetMemberDouble("CHAN_VOICE2", 7.0);
		global.SetMemberDouble("CHAN_VOICE_BASE", 8.0);
		global.SetMemberDouble("CHAN_USER_BASE", 136.0);
		global.SetMemberDouble("TRACER_NONE", 0.0);
		global.SetMemberDouble("TRACER_LINE", 1.0);
		global.SetMemberDouble("TRACER_RAIL", 2.0);
		global.SetMemberDouble("TRACER_BEAM", 3.0);
		global.SetMemberDouble("TRACER_LINE_AND_WHIZ", 4.0);
		table = lua.CreateObject();
		lua.CreateTable();
		table.SetFromStack(-1);
		lua.Pop(1);
		table.SetMemberDouble("HIP", 0.0);
		table.SetMemberDouble("SPINE", 1.0);
		table.SetMemberDouble("SHOULDER", 2.0);
		table.SetMemberDouble("HEAD", 3.0);
		table.SetMemberDouble("SHOULDER_LEFT", 4.0);
		table.SetMemberDouble("ELBOW_LEFT", 5.0);
		table.SetMemberDouble("WRIST_LEFT", 6.0);
		table.SetMemberDouble("HAND_LEFT", 7.0);
		table.SetMemberDouble("SHOULDER_RIGHT", 8.0);
		table.SetMemberDouble("ELBOW_RIGHT", 9.0);
		table.SetMemberDouble("WRIST_RIGHT", 10.0);
		table.SetMemberDouble("HAND_RIGHT", 11.0);
		table.SetMemberDouble("HIP_LEFT", 12.0);
		table.SetMemberDouble("KNEE_LEFT", 13.0);
		table.SetMemberDouble("ANKLE_LEFT", 14.0);
		table.SetMemberDouble("FOOT_LEFT", 15.0);
		table.SetMemberDouble("HIP_RIGHT", 16.0);
		table.SetMemberDouble("KNEE_RIGHT", 17.0);
		table.SetMemberDouble("ANKLE_RIGHT", 18.0);
		table.SetMemberDouble("FOOT_RIGHT", 19.0);
		global.SetMember("SENSORBONE", table);
		lua.DestroyObject(table);
		table = lua.CreateObject();
		lua.CreateTable();
		table.SetFromStack(-1);
		lua.Pop(1);
		table.SetMemberDouble("IN", 1.0);
		table.SetMemberDouble("OUT", 2.0);
		table.SetMemberDouble("MODULATE", 4.0);
		table.SetMemberDouble("STAYOUT", 8.0);
		table.SetMemberDouble("PURGE", 16.0);
		global.SetMember("SCREENFADE", table);
		lua.DestroyObject(table);
		global.SetMemberDouble("SND_NOFLAGS", 0.0);
		global.SetMemberDouble("SND_CHANGE_VOL", 1.0);
		global.SetMemberDouble("SND_CHANGE_PITCH", 2.0);
		global.SetMemberDouble("SND_STOP", 4.0);
		global.SetMemberDouble("SND_SPAWNING", 8.0);
		global.SetMemberDouble("SND_DELAY", 16.0);
		global.SetMemberDouble("SND_STOP_LOOPING", 32.0);
		global.SetMemberDouble("SND_SHOULDPAUSE", 128.0);
		global.SetMemberDouble("SND_IGNORE_PHONEMES", 256.0);
		global.SetMemberDouble("SND_IGNORE_NAME", 512.0);
		global.SetMemberDouble("SND_DO_NOT_OVERWRITE_EXISTING_ON_CHANNEL", 1024.0);
		global.SetMemberDouble("FSOLID_CUSTOMRAYTEST", 1.0);
		global.SetMemberDouble("FSOLID_CUSTOMBOXTEST", 2.0);
		global.SetMemberDouble("FSOLID_NOT_SOLID", 4.0);
		global.SetMemberDouble("FSOLID_TRIGGER", 8.0);
		global.SetMemberDouble("FSOLID_NOT_STANDABLE", 16.0);
		global.SetMemberDouble("FSOLID_VOLUME_CONTENTS", 32.0);
		global.SetMemberDouble("FSOLID_FORCE_WORLD_ALIGNED", 64.0);
		global.SetMemberDouble("FSOLID_USE_TRIGGER_BOUNDS", 128.0);
		global.SetMemberDouble("FSOLID_ROOT_PARENT_ALIGNED", 256.0);
		global.SetMemberDouble("FSOLID_TRIGGER_TOUCH_DEBRIS", 512.0);
		global.SetMemberDouble("FSOLID_MAX_BITS", 10.0);
#if CLIENT_DLL
		global.SetMemberDouble("ANALOG_MOUSE_X", 0.0);
		global.SetMemberDouble("ANALOG_MOUSE_Y", 1.0);
		global.SetMemberDouble("ANALOG_MOUSE_WHEEL", 3.0);
		global.SetMemberDouble("ANALOG_JOY_X", 4.0);
		global.SetMemberDouble("ANALOG_JOY_Y", 5.0);
		global.SetMemberDouble("ANALOG_JOY_Z", 6.0);
		global.SetMemberDouble("ANALOG_JOY_R", 7.0);
		global.SetMemberDouble("ANALOG_JOY_U", 8.0);
		global.SetMemberDouble("ANALOG_JOY_V", 9.0);
		global.SetMemberDouble("IMAGE_FORMAT_DEFAULT", -1.0);
		global.SetMemberDouble("IMAGE_FORMAT_RGBA8888", 0.0);
		global.SetMemberDouble("IMAGE_FORMAT_ABGR8888", 1.0);
		global.SetMemberDouble("IMAGE_FORMAT_RGB888", 2.0);
		global.SetMemberDouble("IMAGE_FORMAT_BGR888", 3.0);
		global.SetMemberDouble("IMAGE_FORMAT_RGB565", 4.0);
		global.SetMemberDouble("IMAGE_FORMAT_ARGB8888", 11.0);
		global.SetMemberDouble("IMAGE_FORMAT_BGRA8888", 12.0);
		global.SetMemberDouble("IMAGE_FORMAT_RGBA16161616F", 24.0);
		global.SetMemberDouble("IMAGE_FORMAT_RGBA16161616", 25.0);
		global.SetMemberDouble("STUDIO_RENDER", 1.0);
		global.SetMemberDouble("STUDIO_VIEWXFORMATTACHMENTS", 2.0);
		global.SetMemberDouble("STUDIO_DRAWTRANSLUCENTSUBMODELS", 4.0);
		global.SetMemberDouble("STUDIO_TWOPASS", 8.0);
		global.SetMemberDouble("STUDIO_STATIC_LIGHTING", 16.0);
		global.SetMemberDouble("STUDIO_WIREFRAME", 32.0);
		global.SetMemberDouble("STUDIO_ITEM_BLINK", 64.0);
		global.SetMemberDouble("STUDIO_NOSHADOWS", 128.0);
		global.SetMemberDouble("STUDIO_WIREFRAME_VCOLLIDE", 256.0);
		global.SetMemberDouble("STUDIO_GENERATE_STATS", 16777216.0);
		global.SetMemberDouble("STUDIO_SSAODEPTHTEXTURE", 134217728.0);
		global.SetMemberDouble("STUDIO_SHADOWDEPTHTEXTURE", 1073741824.0);
		global.SetMemberDouble("STUDIO_TRANSPARENCY", 2147483648.0);
		global.SetMemberDouble("STUDIO_SKIP_DECALS", 268435456.0);
		global.SetMemberDouble("STUDIO_SKIP_FLEXES", 1024.0);
		global.SetMemberDouble("RT_SIZE_NO_CHANGE", 0.0);
		global.SetMemberDouble("RT_SIZE_DEFAULT", 1.0);
		global.SetMemberDouble("RT_SIZE_PICMIP", 2.0);
		global.SetMemberDouble("RT_SIZE_HDR", 3.0);
		global.SetMemberDouble("RT_SIZE_FULL_FRAME_BUFFER", 4.0);
		global.SetMemberDouble("RT_SIZE_OFFSCREEN", 5.0);
		global.SetMemberDouble("RT_SIZE_FULL_FRAME_BUFFER_ROUNDED_UP", 6.0);
		global.SetMemberDouble("RT_SIZE_REPLAY_SCREENSHOT", 7.0);
		global.SetMemberDouble("RT_SIZE_LITERAL", 8.0);
		global.SetMemberDouble("RT_SIZE_LITERAL_PICMIP", 9.0);
		global.SetMemberDouble("MATERIAL_RT_DEPTH_SHARED", 0.0);
		global.SetMemberDouble("MATERIAL_RT_DEPTH_SEPARATE", 1.0);
		global.SetMemberDouble("MATERIAL_RT_DEPTH_NONE", 2.0);
		global.SetMemberDouble("MATERIAL_RT_DEPTH_ONLY", 3.0);
		global.SetMemberDouble("CREATERENDERTARGETFLAGS_HDR", 1.0);
		global.SetMemberDouble("CREATERENDERTARGETFLAGS_AUTOMIPMAP", 2.0);
		global.SetMemberDouble("CREATERENDERTARGETFLAGS_UNFILTERABLE_OK", 4.0);
		global.SetMemberDouble("STENCILOPERATION_KEEP", 1.0);
		global.SetMemberDouble("STENCILOPERATION_ZERO", 2.0);
		global.SetMemberDouble("STENCILOPERATION_REPLACE", 3.0);
		global.SetMemberDouble("STENCILOPERATION_INCRSAT", 4.0);
		global.SetMemberDouble("STENCILOPERATION_DECRSAT", 5.0);
		global.SetMemberDouble("STENCILOPERATION_INVERT", 6.0);
		global.SetMemberDouble("STENCILOPERATION_INCR", 7.0);
		global.SetMemberDouble("STENCILOPERATION_DECR", 8.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_NEVER", 1.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_LESS", 2.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_EQUAL", 3.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_LESSEQUAL", 4.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_GREATER", 5.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_NOTEQUAL", 6.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_GREATEREQUAL", 7.0);
		global.SetMemberDouble("STENCILCOMPARISONFUNCTION_ALWAYS", 8.0);
		global.SetMemberDouble("MATERIAL_FOG_NONE", 0.0);
		global.SetMemberDouble("MATERIAL_FOG_LINEAR", 1.0);
		global.SetMemberDouble("MATERIAL_FOG_LINEAR_BELOW_FOG_Z", 2.0);
		global.SetMemberDouble("MATERIAL_CULLMODE_CCW", 0.0);
		global.SetMemberDouble("MATERIAL_CULLMODE_CW", 1.0);
		global.SetMemberDouble("MATERIAL_CULLMODE_NONE", 2.0);
		global.SetMemberDouble("MATERIAL_POINTS", 0.0);
		global.SetMemberDouble("MATERIAL_LINES", 1.0);
		global.SetMemberDouble("MATERIAL_TRIANGLES", 2.0);
		global.SetMemberDouble("MATERIAL_TRIANGLE_STRIP", 3.0);
		global.SetMemberDouble("MATERIAL_LINE_STRIP", 4.0);
		global.SetMemberDouble("MATERIAL_LINE_LOOP", 5.0);
		global.SetMemberDouble("MATERIAL_POLYGON", 6.0);
		global.SetMemberDouble("MATERIAL_QUADS", 7.0);
		global.SetMemberDouble("MATERIAL_LIGHT_DISABLE", 0.0);
		global.SetMemberDouble("MATERIAL_LIGHT_POINT", 1.0);
		global.SetMemberDouble("MATERIAL_LIGHT_DIRECTIONAL", 2.0);
		global.SetMemberDouble("MATERIAL_LIGHT_SPOT", 3.0);
		global.SetMemberDouble("TEXT_FILTER_UNKNOWN", 0.0);
		global.SetMemberDouble("TEXT_FILTER_GAME_CONTENT", 1.0);
		global.SetMemberDouble("TEXT_FILTER_CHAT", 2.0);
		global.SetMemberDouble("TEXT_FILTER_NAME", 3.0);
		global.SetMemberDouble("GMOD_CHANNEL_STOPPED", 0.0);
		global.SetMemberDouble("GMOD_CHANNEL_PLAYING", 1.0);
		global.SetMemberDouble("GMOD_CHANNEL_PAUSED", 2.0);
		global.SetMemberDouble("GMOD_CHANNEL_STALLED", 3.0);
		global.SetMemberDouble("FFT_256", 0.0);
		global.SetMemberDouble("FFT_512", 1.0);
		global.SetMemberDouble("FFT_1024", 2.0);
		global.SetMemberDouble("FFT_2048", 3.0);
		global.SetMemberDouble("FFT_4096", 4.0);
		global.SetMemberDouble("FFT_8192", 5.0);
		global.SetMemberDouble("FFT_16384", 6.0);
		global.SetMemberDouble("FFT_32768", 7.0);
#else
		table = lua.CreateObject();
		lua.CreateTable();
		table.SetFromStack(-1);
		lua.Pop(1);
		table.SetMemberDouble("NONE", 0.0);
		table.SetMemberDouble("IN_PVS", 1.0);
		table.SetMemberDouble("IDLE_INTERRUPT", 2.0);
		table.SetMemberDouble("LOW_PRIMARY_AMMO", 3.0);
		table.SetMemberDouble("NO_PRIMARY_AMMO", 4.0);
		table.SetMemberDouble("NO_SECONDARY_AMMO", 5.0);
		table.SetMemberDouble("NO_WEAPON", 6.0);
		table.SetMemberDouble("SEE_HATE", 7.0);
		table.SetMemberDouble("SEE_FEAR", 8.0);
		table.SetMemberDouble("SEE_DISLIKE", 9.0);
		table.SetMemberDouble("SEE_ENEMY", 10.0);
		table.SetMemberDouble("LOST_ENEMY", 11.0);
		table.SetMemberDouble("ENEMY_WENT_NULL", 12.0);
		table.SetMemberDouble("ENEMY_OCCLUDED", 13.0);
		table.SetMemberDouble("TARGET_OCCLUDED", 14.0);
		table.SetMemberDouble("HAVE_ENEMY_LOS", 15.0);
		table.SetMemberDouble("HAVE_TARGET_LOS", 16.0);
		table.SetMemberDouble("LIGHT_DAMAGE", 17.0);
		table.SetMemberDouble("HEAVY_DAMAGE", 18.0);
		table.SetMemberDouble("PHYSICS_DAMAGE", 19.0);
		table.SetMemberDouble("REPEATED_DAMAGE", 20.0);
		table.SetMemberDouble("CAN_RANGE_ATTACK1", 21.0);
		table.SetMemberDouble("CAN_RANGE_ATTACK2", 22.0);
		table.SetMemberDouble("CAN_MELEE_ATTACK1", 23.0);
		table.SetMemberDouble("CAN_MELEE_ATTACK2", 24.0);
		table.SetMemberDouble("PROVOKED", 25.0);
		table.SetMemberDouble("NEW_ENEMY", 26.0);
		table.SetMemberDouble("ENEMY_TOO_FAR", 27.0);
		table.SetMemberDouble("ENEMY_FACING_ME", 28.0);
		table.SetMemberDouble("BEHIND_ENEMY", 29.0);
		table.SetMemberDouble("ENEMY_DEAD", 30.0);
		table.SetMemberDouble("ENEMY_UNREACHABLE", 31.0);
		table.SetMemberDouble("SEE_PLAYER", 32.0);
		table.SetMemberDouble("LOST_PLAYER", 33.0);
		table.SetMemberDouble("SEE_NEMESIS", 34.0);
		table.SetMemberDouble("TASK_FAILED", 35.0);
		table.SetMemberDouble("SCHEDULE_DONE", 36.0);
		table.SetMemberDouble("SMELL", 37.0);
		table.SetMemberDouble("TOO_CLOSE_TO_ATTACK", 38.0);
		table.SetMemberDouble("TOO_FAR_TO_ATTACK", 39.0);
		table.SetMemberDouble("NOT_FACING_ATTACK", 40.0);
		table.SetMemberDouble("WEAPON_HAS_LOS", 41.0);
		table.SetMemberDouble("WEAPON_BLOCKED_BY_FRIEND", 42.0);
		table.SetMemberDouble("WEAPON_PLAYER_IN_SPREAD", 43.0);
		table.SetMemberDouble("WEAPON_PLAYER_NEAR_TARGET", 44.0);
		table.SetMemberDouble("WEAPON_SIGHT_OCCLUDED", 45.0);
		table.SetMemberDouble("BETTER_WEAPON_AVAILABLE", 46.0);
		table.SetMemberDouble("HEALTH_ITEM_AVAILABLE", 47.0);
		table.SetMemberDouble("GIVE_WAY", 48.0);
		table.SetMemberDouble("WAY_CLEAR", 49.0);
		table.SetMemberDouble("HEAR_DANGER", 50.0);
		table.SetMemberDouble("HEAR_THUMPER", 51.0);
		table.SetMemberDouble("HEAR_BUGBAIT", 52.0);
		table.SetMemberDouble("HEAR_COMBAT", 53.0);
		table.SetMemberDouble("HEAR_WORLD", 54.0);
		table.SetMemberDouble("HEAR_PLAYER", 55.0);
		table.SetMemberDouble("HEAR_BULLET_IMPACT", 56.0);
		table.SetMemberDouble("HEAR_PHYSICS_DANGER", 57.0);
		table.SetMemberDouble("HEAR_MOVE_AWAY", 58.0);
		table.SetMemberDouble("HEAR_SPOOKY", 59.0);
		table.SetMemberDouble("NO_HEAR_DANGER", 60.0);
		table.SetMemberDouble("FLOATING_OFF_GROUND", 61.0);
		table.SetMemberDouble("MOBBED_BY_ENEMIES", 62.0);
		table.SetMemberDouble("RECEIVED_ORDERS", 63.0);
		table.SetMemberDouble("PLAYER_ADDED_TO_SQUAD", 64.0);
		table.SetMemberDouble("PLAYER_REMOVED_FROM_SQUAD", 65.0);
		table.SetMemberDouble("PLAYER_PUSHING", 66.0);
		table.SetMemberDouble("NPC_FREEZE", 67.0);
		table.SetMemberDouble("NPC_UNFREEZE", 68.0);
		table.SetMemberDouble("TALKER_RESPOND_TO_QUESTION", 69.0);
		table.SetMemberDouble("NO_CUSTOM_INTERRUPTS", 70.0);
		table.SetMemberDouble("LAST_SHARED_CONDITION", 71.0);
		global.SetMember("COND", table);
		lua.DestroyObject(table);
		global.SetMemberDouble("NPC_STATE_INVALID", -1.0);
		global.SetMemberDouble("NPC_STATE_NONE", 0.0);
		global.SetMemberDouble("NPC_STATE_IDLE", 1.0);
		global.SetMemberDouble("NPC_STATE_ALERT", 2.0);
		global.SetMemberDouble("NPC_STATE_COMBAT", 3.0);
		global.SetMemberDouble("NPC_STATE_SCRIPT", 4.0);
		global.SetMemberDouble("NPC_STATE_PLAYDEAD", 5.0);
		global.SetMemberDouble("NPC_STATE_PRONE", 6.0);
		global.SetMemberDouble("NPC_STATE_DEAD", 7.0);
		global.SetMemberDouble("SCHED_NONE", 0.0);
		global.SetMemberDouble("SCHED_IDLE_STAND", 1.0);
		global.SetMemberDouble("SCHED_IDLE_WALK", 2.0);
		global.SetMemberDouble("SCHED_IDLE_WANDER", 3.0);
		global.SetMemberDouble("SCHED_WAKE_ANGRY", 4.0);
		global.SetMemberDouble("SCHED_ALERT_FACE", 5.0);
		global.SetMemberDouble("SCHED_ALERT_FACE_BESTSOUND", 6.0);
		global.SetMemberDouble("SCHED_ALERT_REACT_TO_COMBAT_SOUND", 7.0);
		global.SetMemberDouble("SCHED_ALERT_SCAN", 8.0);
		global.SetMemberDouble("SCHED_ALERT_STAND", 9.0);
		global.SetMemberDouble("SCHED_ALERT_WALK", 10.0);
		global.SetMemberDouble("SCHED_INVESTIGATE_SOUND", 11.0);
		global.SetMemberDouble("SCHED_COMBAT_FACE", 12.0);
		global.SetMemberDouble("SCHED_COMBAT_SWEEP", 13.0);
		global.SetMemberDouble("SCHED_FEAR_FACE", 14.0);
		global.SetMemberDouble("SCHED_COMBAT_STAND", 15.0);
		global.SetMemberDouble("SCHED_COMBAT_WALK", 16.0);
		global.SetMemberDouble("SCHED_CHASE_ENEMY", 17.0);
		global.SetMemberDouble("SCHED_CHASE_ENEMY_FAILED", 18.0);
		global.SetMemberDouble("SCHED_VICTORY_DANCE", 19.0);
		global.SetMemberDouble("SCHED_TARGET_FACE", 20.0);
		global.SetMemberDouble("SCHED_TARGET_CHASE", 21.0);
		global.SetMemberDouble("SCHED_SMALL_FLINCH", 22.0);
		global.SetMemberDouble("SCHED_BIG_FLINCH", 23.0);
		global.SetMemberDouble("SCHED_BACK_AWAY_FROM_ENEMY", 24.0);
		global.SetMemberDouble("SCHED_MOVE_AWAY_FROM_ENEMY", 25.0);
		global.SetMemberDouble("SCHED_BACK_AWAY_FROM_SAVE_POSITION", 26.0);
		global.SetMemberDouble("SCHED_TAKE_COVER_FROM_ENEMY", 27.0);
		global.SetMemberDouble("SCHED_TAKE_COVER_FROM_BEST_SOUND", 28.0);
		global.SetMemberDouble("SCHED_FLEE_FROM_BEST_SOUND", 29.0);
		global.SetMemberDouble("SCHED_TAKE_COVER_FROM_ORIGIN", 30.0);
		global.SetMemberDouble("SCHED_FAIL_TAKE_COVER", 31.0);
		global.SetMemberDouble("SCHED_RUN_FROM_ENEMY", 32.0);
		global.SetMemberDouble("SCHED_RUN_FROM_ENEMY_FALLBACK", 33.0);
		global.SetMemberDouble("SCHED_MOVE_TO_WEAPON_RANGE", 34.0);
		global.SetMemberDouble("SCHED_ESTABLISH_LINE_OF_FIRE", 35.0);
		global.SetMemberDouble("SCHED_ESTABLISH_LINE_OF_FIRE_FALLBACK", 36.0);
		global.SetMemberDouble("SCHED_PRE_FAIL_ESTABLISH_LINE_OF_FIRE", 37.0);
		global.SetMemberDouble("SCHED_FAIL_ESTABLISH_LINE_OF_FIRE", 38.0);
		global.SetMemberDouble("SCHED_SHOOT_ENEMY_COVER", 39.0);
		global.SetMemberDouble("SCHED_COWER", 40.0);
		global.SetMemberDouble("SCHED_MELEE_ATTACK1", 41.0);
		global.SetMemberDouble("SCHED_MELEE_ATTACK2", 42.0);
		global.SetMemberDouble("SCHED_RANGE_ATTACK1", 43.0);
		global.SetMemberDouble("SCHED_RANGE_ATTACK2", 44.0);
		global.SetMemberDouble("SCHED_SPECIAL_ATTACK1", 45.0);
		global.SetMemberDouble("SCHED_SPECIAL_ATTACK2", 46.0);
		global.SetMemberDouble("SCHED_STANDOFF", 47.0);
		global.SetMemberDouble("SCHED_ARM_WEAPON", 48.0);
		global.SetMemberDouble("SCHED_DISARM_WEAPON", 49.0);
		global.SetMemberDouble("SCHED_HIDE_AND_RELOAD", 50.0);
		global.SetMemberDouble("SCHED_RELOAD", 51.0);
		global.SetMemberDouble("SCHED_AMBUSH", 52.0);
		global.SetMemberDouble("SCHED_DIE", 53.0);
		global.SetMemberDouble("SCHED_DIE_RAGDOLL", 54.0);
		global.SetMemberDouble("SCHED_WAIT_FOR_SCRIPT", 55.0);
		global.SetMemberDouble("SCHED_AISCRIPT", 56.0);
		global.SetMemberDouble("SCHED_SCRIPTED_WALK", 57.0);
		global.SetMemberDouble("SCHED_SCRIPTED_RUN", 58.0);
		global.SetMemberDouble("SCHED_SCRIPTED_CUSTOM_MOVE", 59.0);
		global.SetMemberDouble("SCHED_SCRIPTED_WAIT", 60.0);
		global.SetMemberDouble("SCHED_SCRIPTED_FACE", 61.0);
		global.SetMemberDouble("SCHED_SCENE_GENERIC", 62.0);
		global.SetMemberDouble("SCHED_NEW_WEAPON", 63.0);
		global.SetMemberDouble("SCHED_NEW_WEAPON_CHEAT", 64.0);
		global.SetMemberDouble("SCHED_SWITCH_TO_PENDING_WEAPON", 65.0);
		global.SetMemberDouble("SCHED_GET_HEALTHKIT", 66.0);
		global.SetMemberDouble("SCHED_WAIT_FOR_SPEAK_FINISH", 67.0);
		global.SetMemberDouble("SCHED_MOVE_AWAY", 68.0);
		global.SetMemberDouble("SCHED_MOVE_AWAY_FAIL", 69.0);
		global.SetMemberDouble("SCHED_MOVE_AWAY_END", 70.0);
		global.SetMemberDouble("SCHED_FORCED_GO", 71.0);
		global.SetMemberDouble("SCHED_FORCED_GO_RUN", 72.0);
		global.SetMemberDouble("SCHED_NPC_FREEZE", 73.0);
		global.SetMemberDouble("SCHED_PATROL_WALK", 74.0);
		global.SetMemberDouble("SCHED_COMBAT_PATROL", 75.0);
		global.SetMemberDouble("SCHED_PATROL_RUN", 76.0);
		global.SetMemberDouble("SCHED_RUN_RANDOM", 77.0);
		global.SetMemberDouble("SCHED_FALL_TO_GROUND", 78.0);
		global.SetMemberDouble("SCHED_DROPSHIP_DUSTOFF", 79.0);
		global.SetMemberDouble("SCHED_FLINCH_PHYSICS", 80.0);
		global.SetMemberDouble("SCHED_FAIL", 81.0);
		global.SetMemberDouble("SCHED_FAIL_NOSTOP", 82.0);
		global.SetMemberDouble("SCHED_RUN_FROM_ENEMY_MOB", 83.0);
		global.SetMemberDouble("SCHED_DUCK_DODGE", 84.0);
		global.SetMemberDouble("SCHED_INTERACTION_MOVE_TO_PARTNER", 85.0);
		global.SetMemberDouble("SCHED_INTERACTION_WAIT_FOR_PARTNER", 86.0);
		global.SetMemberDouble("SCHED_SLEEP", 87.0);
		global.SetMemberDouble("LAST_SHARED_SCHEDULE", 88.0);
		global.SetMemberDouble("CAP_MOVE_GROUND", 1.0);
		global.SetMemberDouble("CAP_MOVE_JUMP", 2.0);
		global.SetMemberDouble("CAP_MOVE_FLY", 4.0);
		global.SetMemberDouble("CAP_MOVE_CLIMB", 8.0);
		global.SetMemberDouble("CAP_MOVE_SWIM", 16.0);
		global.SetMemberDouble("CAP_MOVE_CRAWL", 32.0);
		global.SetMemberDouble("CAP_MOVE_SHOOT", 64.0);
		global.SetMemberDouble("CAP_SKIP_NAV_GROUND_CHECK", 128.0);
		global.SetMemberDouble("CAP_USE", 256.0);
		global.SetMemberDouble("CAP_AUTO_DOORS", 1024.0);
		global.SetMemberDouble("CAP_OPEN_DOORS", 2048.0);
		global.SetMemberDouble("CAP_TURN_HEAD", 4096.0);
		global.SetMemberDouble("CAP_WEAPON_RANGE_ATTACK1", 8192.0);
		global.SetMemberDouble("CAP_WEAPON_RANGE_ATTACK2", 16384.0);
		global.SetMemberDouble("CAP_WEAPON_MELEE_ATTACK1", 32768.0);
		global.SetMemberDouble("CAP_WEAPON_MELEE_ATTACK2", 65536.0);
		global.SetMemberDouble("CAP_INNATE_RANGE_ATTACK1", 131072.0);
		global.SetMemberDouble("CAP_INNATE_RANGE_ATTACK2", 262144.0);
		global.SetMemberDouble("CAP_INNATE_MELEE_ATTACK1", 524288.0);
		global.SetMemberDouble("CAP_INNATE_MELEE_ATTACK2", 1048576.0);
		global.SetMemberDouble("CAP_USE_WEAPONS", 2097152.0);
		global.SetMemberDouble("CAP_ANIMATEDFACE", 8388608.0);
		global.SetMemberDouble("CAP_USE_SHOT_REGULATOR", 16777216.0);
		global.SetMemberDouble("CAP_FRIENDLY_DMG_IMMUNE", 33554432.0);
		global.SetMemberDouble("CAP_SQUAD", 67108864.0);
		global.SetMemberDouble("CAP_DUCK", 134217728.0);
		global.SetMemberDouble("CAP_NO_HIT_PLAYER", 268435456.0);
		global.SetMemberDouble("CAP_AIM_GUN", 536870912.0);
		global.SetMemberDouble("CAP_NO_HIT_SQUADMATES", 1073741824.0);
		global.SetMemberDouble("CAP_SIMPLE_RADIUS_DAMAGE", -2147483648.0);
		global.SetMemberDouble("HULL_HUMAN", 0.0);
		global.SetMemberDouble("HULL_SMALL_CENTERED", 1.0);
		global.SetMemberDouble("HULL_WIDE_HUMAN", 2.0);
		global.SetMemberDouble("HULL_TINY", 3.0);
		global.SetMemberDouble("HULL_WIDE_SHORT", 4.0);
		global.SetMemberDouble("HULL_MEDIUM", 5.0);
		global.SetMemberDouble("HULL_TINY_CENTERED", 6.0);
		global.SetMemberDouble("HULL_LARGE", 7.0);
		global.SetMemberDouble("HULL_LARGE_CENTERED", 8.0);
		global.SetMemberDouble("HULL_MEDIUM_TALL", 9.0);
		global.SetMemberDouble("NUM_HULLS", 10.0);
		global.SetMemberDouble("CLASS_NONE", 0.0);
		global.SetMemberDouble("CLASS_PLAYER", 1.0);
		global.SetMemberDouble("CLASS_PLAYER_ALLY", 2.0);
		global.SetMemberDouble("CLASS_PLAYER_ALLY_VITAL", 3.0);
		global.SetMemberDouble("CLASS_ANTLION", 4.0);
		global.SetMemberDouble("CLASS_BARNACLE", 5.0);
		global.SetMemberDouble("CLASS_BULLSEYE", 6.0);
		global.SetMemberDouble("CLASS_CITIZEN_PASSIVE", 7.0);
		global.SetMemberDouble("CLASS_CITIZEN_REBEL", 8.0);
		global.SetMemberDouble("CLASS_COMBINE", 9.0);
		global.SetMemberDouble("CLASS_COMBINE_GUNSHIP", 10.0);
		global.SetMemberDouble("CLASS_CONSCRIPT", 11.0);
		global.SetMemberDouble("CLASS_HEADCRAB", 12.0);
		global.SetMemberDouble("CLASS_MANHACK", 13.0);
		global.SetMemberDouble("CLASS_METROPOLICE", 14.0);
		global.SetMemberDouble("CLASS_MILITARY", 15.0);
		global.SetMemberDouble("CLASS_SCANNER", 16.0);
		global.SetMemberDouble("CLASS_STALKER", 17.0);
		global.SetMemberDouble("CLASS_VORTIGAUNT", 18.0);
		global.SetMemberDouble("CLASS_ZOMBIE", 19.0);
		global.SetMemberDouble("CLASS_PROTOSNIPER", 20.0);
		global.SetMemberDouble("CLASS_MISSILE", 21.0);
		global.SetMemberDouble("CLASS_FLARE", 22.0);
		global.SetMemberDouble("CLASS_EARTH_FAUNA", 23.0);
		global.SetMemberDouble("CLASS_HACKED_ROLLERMINE", 24.0);
		global.SetMemberDouble("CLASS_COMBINE_HUNTER", 25.0);
		global.SetMemberDouble("CLASS_MACHINE", 26.0);
		global.SetMemberDouble("CLASS_HUMAN_PASSIVE", 27.0);
		global.SetMemberDouble("CLASS_HUMAN_MILITARY", 28.0);
		global.SetMemberDouble("CLASS_ALIEN_MILITARY", 29.0);
		global.SetMemberDouble("CLASS_ALIEN_MONSTER", 30.0);
		global.SetMemberDouble("CLASS_ALIEN_PREY", 31.0);
		global.SetMemberDouble("CLASS_ALIEN_PREDATOR", 32.0);
		global.SetMemberDouble("CLASS_INSECT", 33.0);
		global.SetMemberDouble("CLASS_PLAYER_BIOWEAPON", 34.0);
		global.SetMemberDouble("CLASS_ALIEN_BIOWEAPON", 35.0);
		global.SetMemberDouble("CLASS_PORTAL_TURRET", 36.0);
		global.SetMemberDouble("NUM_AI_CLASSES", 37.0);
		global.SetMemberDouble("D_ER", 0.0);
		global.SetMemberDouble("D_HT", 1.0);
		global.SetMemberDouble("D_FR", 2.0);
		global.SetMemberDouble("D_LI", 3.0);
		global.SetMemberDouble("D_NU", 4.0);
		global.SetMemberDouble("CT_DEFAULT", 0.0);
		global.SetMemberDouble("CT_DOWNTRODDEN", 1.0);
		global.SetMemberDouble("CT_REFUGEE", 2.0);
		global.SetMemberDouble("CT_REBEL", 3.0);
		global.SetMemberDouble("CT_UNIQUE", 4.0);
		global.SetMemberDouble("SF_CITIZEN_FOLLOW", 65536.0);
		global.SetMemberDouble("SF_CITIZEN_MEDIC", 131072.0);
		global.SetMemberDouble("SF_CITIZEN_RANDOM_HEAD", 262144.0);
		global.SetMemberDouble("SF_CITIZEN_AMMORESUPPLIER", 524288.0);
		global.SetMemberDouble("SF_CITIZEN_NOT_COMMANDABLE", 1048576.0);
		global.SetMemberDouble("SF_CITIZEN_IGNORE_SEMAPHORE", 2097152.0);
		global.SetMemberDouble("SF_CITIZEN_RANDOM_HEAD_MALE", 4194304.0);
		global.SetMemberDouble("SF_CITIZEN_RANDOM_HEAD_FEMALE", 8388608.0);
		global.SetMemberDouble("SF_CITIZEN_USE_RENDER_BOUNDS", 16777216.0);
		global.SetMemberDouble("SF_NPC_WAIT_TILL_SEEN", 1.0);
		global.SetMemberDouble("SF_NPC_GAG", 2.0);
		global.SetMemberDouble("SF_NPC_FALL_TO_GROUND", 4.0);
		global.SetMemberDouble("SF_NPC_DROP_HEALTHKIT", 8.0);
		global.SetMemberDouble("SF_NPC_START_EFFICIENT", 16.0);
		global.SetMemberDouble("SF_NPC_WAIT_FOR_SCRIPT", 128.0);
		global.SetMemberDouble("SF_NPC_LONG_RANGE", 256.0);
		global.SetMemberDouble("SF_NPC_FADE_CORPSE", 512.0);
		global.SetMemberDouble("SF_NPC_ALWAYSTHINK", 1024.0);
		global.SetMemberDouble("SF_NPC_TEMPLATE", 2048.0);
		global.SetMemberDouble("SF_NPC_ALTCOLLISION", 4096.0);
		global.SetMemberDouble("SF_NPC_NO_WEAPON_DROP", 8192.0);
		global.SetMemberDouble("SF_NPC_NO_PLAYER_PUSHAWAY", 16384.0);
		global.SetMemberDouble("SF_ROLLERMINE_FRIENDLY", 65536.0);
		global.SetMemberDouble("SF_FLOOR_TURRET_CITIZEN", 512.0);
		global.SetMemberDouble("NAV_MESH_INVALID", 0.0);
		global.SetMemberDouble("NAV_MESH_CROUCH", 1.0);
		global.SetMemberDouble("NAV_MESH_JUMP", 2.0);
		global.SetMemberDouble("NAV_MESH_PRECISE", 4.0);
		global.SetMemberDouble("NAV_MESH_NO_JUMP", 8.0);
		global.SetMemberDouble("NAV_MESH_STOP", 16.0);
		global.SetMemberDouble("NAV_MESH_RUN", 32.0);
		global.SetMemberDouble("NAV_MESH_WALK", 64.0);
		global.SetMemberDouble("NAV_MESH_AVOID", 128.0);
		global.SetMemberDouble("NAV_MESH_TRANSIENT", 256.0);
		global.SetMemberDouble("NAV_MESH_DONT_HIDE", 512.0);
		global.SetMemberDouble("NAV_MESH_STAND", 1024.0);
		global.SetMemberDouble("NAV_MESH_NO_HOSTAGES", 2048.0);
		global.SetMemberDouble("NAV_MESH_STAIRS", 4096.0);
		global.SetMemberDouble("NAV_MESH_NO_MERGE", 8192.0);
		global.SetMemberDouble("NAV_MESH_OBSTACLE_TOP", 16384.0);
		global.SetMemberDouble("NAV_MESH_CLIFF", 32768.0);
		global.SetMemberDouble("NAV_MESH_BLOCKED_LUA", 65536.0);
		global.SetMemberDouble("NAV_MESH_BLOCKED_PROPDOOR", 268435456.0);
		global.SetMemberDouble("NAV_MESH_FUNC_COST", 536870912.0);
		global.SetMemberDouble("NAV_MESH_HAS_ELEVATOR", 1073741824.0);
		global.SetMemberDouble("NAV_MESH_NAV_BLOCKER", -2147483648.0);
		global.SetMemberDouble("GLOBAL_OFF", 0.0);
		global.SetMemberDouble("GLOBAL_ON", 1.0);
		global.SetMemberDouble("GLOBAL_DEAD", 2.0);
		global.SetMemberDouble("SOUND_NONE", 0.0);
		global.SetMemberDouble("SOUND_COMBAT", 1.0);
		global.SetMemberDouble("SOUND_WORLD", 2.0);
		global.SetMemberDouble("SOUND_PLAYER", 4.0);
		global.SetMemberDouble("SOUND_DANGER", 8.0);
		global.SetMemberDouble("SOUND_BULLET_IMPACT", 16.0);
		global.SetMemberDouble("SOUND_CARCASS", 32.0);
		global.SetMemberDouble("SOUND_MEAT", 64.0);
		global.SetMemberDouble("SOUND_GARBAGE", 128.0);
		global.SetMemberDouble("SOUND_THUMPER", 256.0);
		global.SetMemberDouble("SOUND_BUGBAIT", 512.0);
		global.SetMemberDouble("SOUND_PHYSICS_DANGER", 1024.0);
		global.SetMemberDouble("SOUND_DANGER_SNIPERONLY", 2048.0);
		global.SetMemberDouble("SOUND_MOVE_AWAY", 4096.0);
		global.SetMemberDouble("SOUND_PLAYER_VEHICLE", 8192.0);
		global.SetMemberDouble("SOUND_READINESS_LOW", 16384.0);
		global.SetMemberDouble("SOUND_READINESS_MEDIUM", 32768.0);
		global.SetMemberDouble("SOUND_READINESS_HIGH", 65536.0);
		global.SetMemberDouble("SOUND_CONTEXT_FROM_SNIPER", 1048576.0);
		global.SetMemberDouble("SOUND_CONTEXT_GUNFIRE", 2097152.0);
		global.SetMemberDouble("SOUND_CONTEXT_MORTAR", 4194304.0);
		global.SetMemberDouble("SOUND_CONTEXT_COMBINE_ONLY", 8388608.0);
		global.SetMemberDouble("SOUND_CONTEXT_REACT_TO_SOURCE", 16777216.0);
		global.SetMemberDouble("SOUND_CONTEXT_EXPLOSION", 33554432.0);
		global.SetMemberDouble("SOUND_CONTEXT_EXCLUDE_COMBINE", 67108864.0);
		global.SetMemberDouble("SOUND_CONTEXT_DANGER_APPROACH", 134217728.0);
		global.SetMemberDouble("SOUND_CONTEXT_ALLIES_ONLY", 268435456.0);
		global.SetMemberDouble("SOUND_CONTEXT_PLAYER_VEHICLE", 536870912.0);
		global.SetMemberDouble("NAV_NONE", -1.0);
		global.SetMemberDouble("NAV_GROUND", 0.0);
		global.SetMemberDouble("NAV_JUMP", 1.0);
		global.SetMemberDouble("NAV_FLY", 2.0);
		global.SetMemberDouble("NAV_CLIMB", 3.0);
		global.SetMemberDouble("TASKSTATUS_NEW", 0.0);
		global.SetMemberDouble("TASKSTATUS_RUN_MOVE_AND_TASK", 1.0);
		global.SetMemberDouble("TASKSTATUS_RUN_MOVE", 2.0);
		global.SetMemberDouble("TASKSTATUS_RUN_TASK", 3.0);
		global.SetMemberDouble("TASKSTATUS_COMPLETE", 4.0);
		global.SetMemberDouble("AIMR_BLOCKED_ENTITY", -1.0);
		global.SetMemberDouble("AIMR_BLOCKED_WORLD", -2.0);
		global.SetMemberDouble("AIMR_BLOCKED_NPC", -3.0);
		global.SetMemberDouble("AIMR_ILLEGAL", -4.0);
		global.SetMemberDouble("AIMR_OK", 0.0);
		global.SetMemberDouble("AIMR_CHANGE_TYPE", 1.0);
#endif
	}
}
#endif
