global using static Game.Shared.HL2.HL2CollisionGroups;

using Source;

namespace Game.Shared.HL2;

public static class HL2CollisionGroups {
	public const CollisionGroup HL2COLLISION_GROUP_PLASMANODE = CollisionGroup.LastSharedCollisionGroup;
	public const CollisionGroup HL2COLLISION_GROUP_SPIT = HL2COLLISION_GROUP_PLASMANODE + 1;
	public const CollisionGroup HL2COLLISION_GROUP_HOMING_MISSILE = HL2COLLISION_GROUP_PLASMANODE + 2;
	public const CollisionGroup HL2COLLISION_GROUP_COMBINE_BALL = HL2COLLISION_GROUP_PLASMANODE + 3;

	public const CollisionGroup HL2COLLISION_GROUP_FIRST_NPC= HL2COLLISION_GROUP_PLASMANODE + 4;
	public const CollisionGroup HL2COLLISION_GROUP_HOUNDEYE= HL2COLLISION_GROUP_PLASMANODE + 5;
	public const CollisionGroup HL2COLLISION_GROUP_CROW= HL2COLLISION_GROUP_PLASMANODE + 6;
	public const CollisionGroup HL2COLLISION_GROUP_HEADCRAB= HL2COLLISION_GROUP_PLASMANODE + 7;
	public const CollisionGroup HL2COLLISION_GROUP_STRIDER= HL2COLLISION_GROUP_PLASMANODE + 8;
	public const CollisionGroup HL2COLLISION_GROUP_GUNSHIP= HL2COLLISION_GROUP_PLASMANODE + 9;
	public const CollisionGroup HL2COLLISION_GROUP_ANTLION= HL2COLLISION_GROUP_PLASMANODE + 10;
	public const CollisionGroup HL2COLLISION_GROUP_LAST_NPC= HL2COLLISION_GROUP_PLASMANODE + 11;
	public const CollisionGroup HL2COLLISION_GROUP_COMBINE_BALL_NPC = HL2COLLISION_GROUP_PLASMANODE + 12;
}
