global using static Source.Dbg;
global using static Source.Common.CFormatting;
global using static Source.PlatformMacros;
global using static Source.Common.MemUtils;
global using static Source.Common.ThreadUtils;
global using static Source.Common.Engine.ImportUtils;
global using static Source.Common.Mathematics.MathLibConsts;
global using static Source.GlobalReflectionUtils;
global using static Source.Common.RecvPropHelpers;
global using static Source.Common.SendPropHelpers;
global using static Source.Common.GameEventConstants;
global using static Source.Common.RandomGlobals;
global using static Source.Common.Utilities.UtlSymbolGlobals;
global using static Source.Common.Physics.PhysicsConversions;
global using static Source.Common.Filesystem.FilesystemGlobals;
global using CRC32_t = uint;
global using HCursor = nint;
global using UtlSymId_t = ulong;
global using vec_t = float;
global using FileNameHandle_t = ulong;
global using FileFindHandle_t = ulong;
global using PackedEntityHandle_t = nint;
global using LightCacheHandle_t = nint;
global using SpatialPartitionHandle_t = ushort;
global using TimeUnit_t = double;
global using MDLHandle_t = uint;
global using ModelInstanceHandle_t = uint;
global using SoundSource = int;
global using HTOOLHANDLE = uint;
global using QueryCvarCookie_t = int;
global using static Source.Common.DataCache.DataCacheConsts;
global using WorldDecalHandle_t = ushort;
global using ShadowDecalHandle_t = ushort;
global using OverlayFragmentHandle_t = ushort;
global using WeaponInfoFileHandle_t = ushort;
global using Trace = Source.Common.GameTrace;
global using ViewRects = Source.Common.Utilities.RefStack<Source.Common.Engine.ViewRect>;
global using ClientRenderHandle_t = long;
global using ClientEntityHandle = Source.Common.BaseHandle;
global using ClientThinkHandle_t = ulong;
global using static Source.Common.ClientRenderHandleGlobals;
global using static Source.Common.Audio.AudioConstants;
global using static Source.Common.SoundConstants;
