using Source;
using Source.Common.Commands;
using Source.Common.GarrysMod.Lua;

namespace Game.Lua;

public class LuaInterfaceImpl : ILuaInterface
{
	public int AddThreadedCall(ILuaThreadedCall call) => throw new NotImplementedException();
	public void AppendStackTrace(Span<char> chars) => throw new NotImplementedException();
	public void ArgError(int argNum, ReadOnlySpan<char> strMessage) => throw new NotImplementedException();
	public void Call(int args, int results) => throw new NotImplementedException();
	public bool CallFunctionProtected(int unk1, int unk2, bool unk3) => throw new NotImplementedException();
	public void CallInternal(int args, int rets) => throw new NotImplementedException();
	public bool CallInternalGet(int args, ILuaObject obj) => throw new NotImplementedException();
	public bool CallInternalGetBool(int args) => throw new NotImplementedException();
	public ReadOnlySpan<char> CallInternalGetString(int args) => throw new NotImplementedException();
	public void CallInternalNoReturns(int args) => throw new NotImplementedException();
	public double CheckNumber(int stackPos = -1) => throw new NotImplementedException();
	public double CheckNumberOpt(int stackPos, double def) => throw new NotImplementedException();
	public ReadOnlySpan<char> CheckString(int stackPos = -1) => throw new NotImplementedException();
	public ReadOnlySpan<char> CheckStringOpt(int stackPos, ReadOnlySpan<char> def) => throw new NotImplementedException();
	public void CheckType(int stackPos, int type) => throw new NotImplementedException();
	public ConCommand CreateConCommand(ReadOnlySpan<char> name, ReadOnlySpan<char> helpString, int flags, FnCommandCallback? callback, FnCommandCompletionCallback? completionCallback) => throw new NotImplementedException();
	public ConVar CreateConVar(ReadOnlySpan<char> name, ReadOnlySpan<char> defaultValue, ReadOnlySpan<char> helpString, int flags) => throw new NotImplementedException();
	public void CreateMetaTableType(ReadOnlySpan<char> strName, int type) => throw new NotImplementedException();
	public ILuaObject CreateObject() => throw new NotImplementedException();
	public void CreateTable() => throw new NotImplementedException();
	public void Cycle() => throw new NotImplementedException();
	public void DestroyObject(ILuaObject obj) => throw new NotImplementedException();
	public int Equal(int a, int b) => throw new NotImplementedException();
	public void Error(ReadOnlySpan<char> err) => throw new NotImplementedException();
	public void ErrorFromLua(ReadOnlySpan<char> msg) => throw new NotImplementedException();
	public void ErrorNoHalt(ReadOnlySpan<char> msg) => throw new NotImplementedException();
	public bool FindAndRunScript(ReadOnlySpan<char> filename, bool run, bool showErrors, ReadOnlySpan<char> stringToRun, bool noReturns) => throw new NotImplementedException();
	public bool FindObjectOnTable(int tableIndex, int keyIndex) => throw new NotImplementedException();
	public bool FindOnObjectsMetaTable(int objIndex, int keyIndex) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetActualTypeName(int type) => throw new NotImplementedException();
	public bool GetBool(int stackPos = -1) => throw new NotImplementedException();
	public CFunc GetCFunction(int stackPos = -1) => throw new NotImplementedException();
	public int GetColor(int index) => throw new NotImplementedException();
	public void GetCurrentFile(out string outStr) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetCurrentLocation() => throw new NotImplementedException();
	public void GetDataString(int index, out ReadOnlySpan<char> str) => throw new NotImplementedException();
	public void GetField(int stackPos, ReadOnlySpan<char> strName) => throw new NotImplementedException();
	public int GetFlags(int index) => throw new NotImplementedException();
	public int GetInfo(ReadOnlySpan<char> what, ref lua_Debug dbg) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetLocal(ref lua_Debug dbg, int n) => throw new NotImplementedException();
	public bool GetMetaTable(int i) => throw new NotImplementedException();
	public ILuaObject GetMetaTableObject(ReadOnlySpan<char> name, int type) => throw new NotImplementedException();
	public ILuaObject GetMetaTableObject(int index) => throw new NotImplementedException();
	public ILuaObject GetNewTable() => throw new NotImplementedException();
	public double GetNumber(int stackPos = -1) => throw new NotImplementedException();
	public ILuaObject GetObject(int index) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetPath() => throw new NotImplementedException();
	public ReadOnlySpan<char> GetPathID() => throw new NotImplementedException();
	public ReadOnlySpan<char> GetPooledString(int index) => throw new NotImplementedException();
	public ILuaObject GetReturn(int index) => throw new NotImplementedException();
	public int GetStack(int level, ref lua_Debug dbg) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetString(int stackPos = -1) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetStringOrError(int index) => throw new NotImplementedException();
	public void GetTable(int stackPos) => throw new NotImplementedException();
	public int GetType(int stackPos) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetTypeName(int type) => throw new NotImplementedException();
	public ReadOnlySpan<char> GetUpvalue(int funcIndex, int n) => throw new NotImplementedException();
	public unsafe void* GetUserdata(int stackPos = -1) => throw new NotImplementedException();
	public ILuaObject Global() => throw new NotImplementedException();
	public bool Init(ILuaGameCallback callbacks, bool unk) => throw new NotImplementedException();
	public void Insert(int stackPos) => throw new NotImplementedException();
	public bool IsClient() => throw new NotImplementedException();
	public bool IsEqual(ILuaObject objA, ILuaObject objB) => throw new NotImplementedException();
	public bool IsMenu() => throw new NotImplementedException();
	public bool IsServer() => throw new NotImplementedException();
	public bool IsType(int stackPos, int type) => throw new NotImplementedException();
	public bool isUserData(int index) => throw new NotImplementedException();
	public void LuaError(ReadOnlySpan<char> err, int index) => throw new NotImplementedException();
	public void Msg(ReadOnlySpan<char> msg) => throw new NotImplementedException();
	public void MsgColour(in Color col, ReadOnlySpan<char> msg) => throw new NotImplementedException();
	public void NewGlobalTable(ReadOnlySpan<char> name) => throw new NotImplementedException();
	public ILuaObject NewTemporaryObject() => throw new NotImplementedException();
	public unsafe void* NewUserdata(uint size) => throw new NotImplementedException();
	public int Next(int stackPos) => throw new NotImplementedException();
	public int PCall(int args, int results, int errorFunc) => throw new NotImplementedException();
	public void Pop(int iAmt = 1) => throw new NotImplementedException();
	public void PopPath() => throw new NotImplementedException();
	public void PreCreateTable(int arrelems, int nonarrelems) => throw new NotImplementedException();
	public void Push(int stackPos) => throw new NotImplementedException();
	public void PushBool(bool val) => throw new NotImplementedException();
	public void PushCClosure(CFunc val, int vars) => throw new NotImplementedException();
	public void PushCFunction(CFunc val) => throw new NotImplementedException();
	public nint PushColor(Color color) => throw new NotImplementedException();
	public void PushLong(long num) => throw new NotImplementedException();
	public void PushLuaFunction(CFunc func) => throw new NotImplementedException();
	public void PushLuaObject(ILuaObject obj) => throw new NotImplementedException();
	public void PushNil() => throw new NotImplementedException();
	public void PushNumber(double val) => throw new NotImplementedException();
	public void PushPath(ReadOnlySpan<char> path) => throw new NotImplementedException();
	public void PushPooledString(int index) => throw new NotImplementedException();
	public void PushSpecial(int type) => throw new NotImplementedException();
	public void PushString(ReadOnlySpan<char> val) => throw new NotImplementedException();
	public unsafe void PushUserdata(void* userdata) => throw new NotImplementedException();
	public int RawEqual(int a, int b) => throw new NotImplementedException();
	public void RawGet(int stackPos) => throw new NotImplementedException();
	public void RawSet(int stackPos) => throw new NotImplementedException();
	public int ReferenceCreate() => throw new NotImplementedException();
	public void ReferenceFree(int i) => throw new NotImplementedException();
	public void ReferencePush(int i) => throw new NotImplementedException();
	public int RegisterMetaTable(ReadOnlySpan<char> name, ILuaObject tbl) => throw new NotImplementedException();
	public void Remove(int stackPos) => throw new NotImplementedException();
	public void Require(ReadOnlySpan<char> name) => throw new NotImplementedException();
	public bool RunLuaModule(ReadOnlySpan<char> name) => throw new NotImplementedException();
	public bool RunString(ReadOnlySpan<char> filename, ReadOnlySpan<char> path, ReadOnlySpan<char> stringToRun, bool run, bool showErrors) => throw new NotImplementedException();
	public bool RunStringEx(ReadOnlySpan<char> filename, ReadOnlySpan<char> path, ReadOnlySpan<char> stringToRun, bool run, bool printErrors, bool dontPushErrors, bool noReturns) => throw new NotImplementedException();
	public void SetField(int stackPos, ReadOnlySpan<char> strName) => throw new NotImplementedException();
	public void SetMember(ILuaObject table, ILuaObject key, ILuaObject value) => throw new NotImplementedException();
	public void SetMember(ILuaObject table, float key) => throw new NotImplementedException();
	public void SetMember(ILuaObject table, float key, ILuaObject value) => throw new NotImplementedException();
	public void SetMember(ILuaObject table, ReadOnlySpan<char> key) => throw new NotImplementedException();
	public void SetMember(ILuaObject table, ReadOnlySpan<char> key, ILuaObject value) => throw new NotImplementedException();
	public void SetMemberFast(ILuaObject table, int keyIndex, int valueIndex) => throw new NotImplementedException();
	public void SetMetaTable(int i) => throw new NotImplementedException();
	public void SetPathID(ReadOnlySpan<char> pathID) => throw new NotImplementedException();
	public void SetTable(int i) => throw new NotImplementedException();
	public void SetType(byte unk) => throw new NotImplementedException();
	public void Shutdown() => throw new NotImplementedException();
	public void ThrowError(ReadOnlySpan<char> strError) => throw new NotImplementedException();
	public int Top() => throw new NotImplementedException();
	public void TypeError(ReadOnlySpan<char> name, int index) => throw new NotImplementedException();
}
